### ISSUE TITLE
RC6 Performance Degradation 

### ISSUE THREAD

**Issue by amcdnl** [swimlane/angular2-data-table#102]
Upon upgrading from Angular2 from RC5 to RC6, there is a performance degradation on virtual scrolling. Need to research further before upgrading.

Branch: https://github.com/swimlane/angular2-data-table/tree/rc6

**Comment by dmittendorf** [comment]
Might be due to this bug, which has been fixed in angular:

https://github.com/angular/angular/issues/11371

**Comment by amcdnl** [comment]
Ya, thats probably it. I went ahead and upgraded and will continue to monitor. Thanks for sharing!

**Comment by amcdnl** [comment]
This still occurs in RC7 :(

**Comment by amcdnl** [comment]
Fixed in 2.0!!!
