### ISSUE TITLE
Multiple tables on same page all reflect same properties

### ISSUE THREAD

**Issue by amcdnl** [swimlane/angular2-data-table#103]
## Description
Multiple tables on the same page all reflect same rows/options. This problem was introduced in RC4. Reference: https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-module-provider-visibility

## Considerations
I've tried removing the `StateService` provider from the module (see: https://github.com/swimlane/angular2-data-table/blob/master/src/angular2-data-table.ts#L63 ) and just add it to the top component ( `components/DataTable.ts` ), but then child components such as the Body component ( https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/Body.ts#L71 ) do not have access to that provider due to scoping. When adding the provider to each child component, the state service is a new instance each time.

@DzmitryShylovich suggested doing something similar to material's registry on Gitter. See:

> another solution might be to store table states as a map in StateService like here https://github.com/angular/material2/blob/master/src/lib/icon/icon-registry.ts#L53

Have not pursued this much more due to the LOE of that and unknown impacts.

One options might be to just remove the service from being injected altogether and just make it a regular class and pass it down to all child components but again high LOE and then makes code much messier.

**Comment by Tempus35** [comment]
Have what I think is a working version using maps in the service with each table having a unique key to store their data. There is some small issue with pager, need to figure that out and I also need to clean it up and fix typescript warnings. After all that I will make a PR.

**Comment by jimitndiaye** [comment]
Providing StateService at the DataTable level should provide that single instance to all child components, including the body. Is Body being added as a content child or a view child? You may need to use the @Host() decorator on the child components to force it to use the ambient StateService.

**Comment by amcdnl** [comment]
@jimitndiaye  Interesting! Do you have any code samples of what that looks like as this is news to me!
