### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by ringodotnl** [swimlane/angular2-data-table#109]
Getting error: "Template parse errors:↵Can't bind to 'rows' since it isn't a known property of 'datatable'.
Using RC6 / TS 2

**Comment by amcdnl** [comment]
Please post a plunkr demo

**Comment by duncanmcmillan** [comment]
Hi ringodotnl
I am also getting this issue trying to use your ngx-datatable in a app built with Angular2_rc5 , ts2 and webpack, could you advise whey this issue was closed please.

Thanks

Duncan

**Comment by amcdnl** [comment]
We only support latest, upgrade to 2.4 and try it.
