### ISSUE TITLE
Book iframe gistrun

### ISSUE THREAD

**Issue by 0x003e** [swimlane/angular2-data-table#11]
Hi,
Demo sample code don't work with the iframe (Chrome Version 50.0.2661.86 (64-bit))
:
![selection_008](https://cloud.githubusercontent.com/assets/12722481/16605391/cc27e5b8-432e-11e6-9359-b05b589a021d.png)
https://swimlane.gitbooks.io/angular2-data-table/content/examples/paging.html

**However it works fine on firefox**

**Comment by amcdnl** [comment]
It actually works fine for me, is there any errors?

**Comment by cesarp** [comment]
Same issue for me, this is the error I see when trying to load the gist:

```json
{
  "message": "API rate limit exceeded for 200.52.87.204. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by amcdnl** [comment]
Switch from github to npmcdn - https://npmcdn.com/angular2-data-table :)
