### ISSUE TITLE
"npm install angular2-data-table "   don't work

### ISSUE THREAD

**Issue by hellogithub2014** [swimlane/angular2-data-table#110]
Hello!   I was following [https://swimlane.gitbooks.io/angular2-data-table/content/introduction/installing.html](url)  to install angular2-data-table, but failed.
# **Here is the wrong:**

`F:\SublimeWorkspace\data-table-6>npm install angular2-data-table
angular2-quickstart@1.0.0 F:\SublimeWorkspace\data-table-6
+-- angular2-data-table@0.4.0  extraneous
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN angular2-data-table@0.4.0 requires a peer of rxjs@5.0.0-beta.6 but none
 was installed.
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.`

# **here is my "package.json":**

`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "systemjs": "0.19.27",    
    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6",

    "typescript":"2.0.2",
    "@angular/platform-server": "2.0.0-rc.6",
    "rxjs": "5.0.0-beta.11",
    "zone.js": "0.6.17"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^1.8.10",
    "typings":"^1.3.2"
  }
}
`   
I tried to change my rxjs to 5.0.0-beta.6， but then my @angular/core、@angular/compiler、and other 
angular2 model got wrong.

what should i do?   thanks everyone~~~

**Comment by amcdnl** [comment]
Please provide a demo repo.

**Comment by hellogithub2014** [comment]
@amcdnl    I'm new to github , don't know how to provide a demo repo,(；′⌒`)    but here  is the zip of my demo.

**Comment by hellogithub2014** [comment]
@amcdnl  sorry, i'm new to github, don't know how to provide a demo repo.  But I can post all my code files below,here are them:
Sorry, Even I will think this might be too long~~~ 
**system.config.js:**
`/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs':                       'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
      'angular2-data-table': 'npm:angular2-data-table'

    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      }
    }
  });
})(this);
`
**tsconfig.json**
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
`
**typings.json**
`{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160831021119"
  }
}
`
**app.component.ts**
`import {Component} from '@angular/core'

import { Angular2DataTableModule } from 'angular2-data-table';

import {
	TableOptions,
	TableColumn,
	ColumnMode
} from 'angular2-data-table';

@Component({
	selector: 'my-app',
	template: `
  	<h1>My First Angular 2 App</h1>
  	<div>
  	      <h3>basic</h3>
  	      <datatable
  	        class='material striped'
  	        [rows]='rows'
  	        [options]='options'
  	         (onPageChange)='onPage($event)'>
  	      </datatable>
  	    </div>
  	`
})
export class AppComponent {

	rows = [];

	options = new TableOptions({
		columnMode: ColumnMode.force,
		headerHeight: 50,
		footerHeight: 50,
		rowHeight: 'auto',
		externalPaging: true,
		limit: 10,
		columns: [
			new TableColumn({ prop: 'name' }),
			new TableColumn({ name: 'Gender' }),
			new TableColumn({ name: 'Company' })
		]
	});

	constructor() {
		this.page();
	}
	
	page() {
		this.fetch((results) => {
			this.options.count = results.length;
			let start = this.options.offset * this.options.limit;
			let end = start + this.options.limit;

			// let paged = results.slice(start, end);

			// splice doesn't let u insert at
			// a new out of bounds index :(
			// this.rows.splice(0, this.rows.length);
			// this.rows.push(...paged)
			// this.rows.splice(start, 0, ...paged);

			for (let i = start; i < end; i++) {
				this.rows[i] = results[i];
			}

			console.log('updated', start, end, this.rows);
		});
	}

	fetch(cb) {
		const req = new XMLHttpRequest();
		req.open('GET', `app/company.json`);

		req.onload = () => {
			cb(JSON.parse(req.response));
		};

		req.send();
	}

	onPage({ offset, limit, count }) {
		console.log('Paged!', offset, limit, count);
		this.page(); 
	}

}`

**app.module.ts**
`import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';


import { Angular2DataTableModule } from 'angular2-data-table';


@NgModule({
    imports:      [ BrowserModule,Angular2DataTableModule ],
    declarations: [ AppComponent ],
    bootstrap:    [ AppComponent ]
})
export class AppModule { }`

**main.ts**
`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);
`

**Comment by amcdnl** [comment]
I'm gonna need a demo repo, I can't repo based on the above.

**Comment by amcdnl** [comment]
Closing due to no reply.
