### ISSUE TITLE
DataTableColumn.js:7 Uncaught ReferenceError: __decorate is not defined

### ISSUE THREAD

**Issue by katsuki-nakatani** [swimlane/angular2-data-table#111]
angular2 rc6.
1.0.0-beta.11-webpack.8.

start up page error 

DataTableColumn.js:7 Uncaught ReferenceError: __decorate is not defined

Can you help.

**Comment by Tempus35** [comment]
This happened to me, I had to change the tsconfig to allow emitting of helper functions and then recompile the code, the _decorate function etc is missing from some JS otherwise..

**Comment by amcdnl** [comment]
@Tempus35 is this a recent change? Are u using TypeScript or JS w/ ng2?

**Comment by Tempus35** [comment]
I am using Typescript and SystemJS with ng2. I have had to do the above for a while, I have tried using umd version but get some odd errors, so I switched to the cjs one and got that decorate error. After some research I found it was missing the helpers and that emit helpers in tsconfig was set to false. Changed that to true, re-ran npm run release and used the resulting code.
