### ISSUE TITLE
Page count message customization

### ISSUE THREAD

**Issue by jntakpe** [swimlane/angular2-data-table#113]
### Current behaviour

Displaying `{{state.rowCount}} total`
### Expected behaviour

Being able to customize the message

**Comment by amcdnl** [comment]
How about a template option?

**Comment by jntakpe** [comment]
Seems good to me

**Comment by be4code** [comment]
Is there any chance that you implement this feature?

**Comment by amcdnl** [comment]
I plan on it, just lower priority. If you want to give it a shot I can show you where.

**Comment by amcdnl** [comment]
Done in latest
