### ISSUE TITLE
Failed to run the demo with syntax error.

### ISSUE THREAD

**Issue by gtvforever** [swimlane/angular2-data-table#117]
Just clone the repo and run the command ' npm start', but i got below error messages.

C:\Users\guomingz\angular2-data-table>npm start

> angular2-data-table@0.4.0 start C:\Users\guomingz\angular2-data-table
> webpack-dev-server

C:\Users\guomingz\angular2-data-table\webpack.config.js:17
function webpackConfig(options = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\guomingz\angular2-data-table\node_modules\webpack\bin\convert-argv.js:93:13)
    at Object.<anonymous> (C:\Users\guomingz\angular2-data-table\node_modules\webpack-dev-server\bin\webpack-dev-server.js:127:48)
    at Module._compile (module.js:409:26)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\guomingz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.4.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-data-table@0.4.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\guomingz\angular2-data-table\npm-debug.log

**Comment by amcdnl** [comment]
Please provide a demo repo, as I do not see this.

**Comment by trf19** [comment]
I can confirm this. I cloned the whole repo. Then I ran 

`npm 
npm start`

Output:


>npm start
> angular2-data-table@0.5.2 start \angular2-data-table-master
> webpack-dev-server
\angular2-data-table-master\webpack.config.js:17
function webpackConfig(options = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (\angular2-data-table-master\node_modules\webpack\bin\convert-argv.js:93:13)
    at Object.<anonymous> (\angular2-data-table-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:127:48)
    at Module._compile (module.js:409:26)

Windows_NT 10.0.10586
node v4.5.0
npm  v3.10.6

**Comment by amcdnl** [comment]
Node version?

**Comment by gtvforever** [comment]
4.4.5

**Comment by gtvforever** [comment]
Hello amcdnl,

i just pulled the latest code and got the same error again. Below is my log info, i didn't modify any code besides ran 'npm install'.

PS C:\Users\guomingz\angular2-data-table> git log
commit ff23835378c7b2ddf9ea0267f6c4e4a28627f9c0
Merge: 7e55be9 833d1d0
Author: Austin <amcdaniel2@gmail.com>
Date:   Mon Sep 12 08:15:48 2016 -0400

    Merge pull request #112 from ocombe/patch-2

    fixed dependencies for rc6

commit 833d1d0dcc620ec58df65d8174fbe52e170ef8ed
Author: Olivier Combe <olivier.combe@gmail.com>
Date:   Mon Sep 12 08:58:09 2016 +0200

    fixed dependencies for rc6

    removed rxjs & zonejs peer dependencies, as @angular already requires them

commit 7e55be9e12b52a19dcfd8adb0b1d603658842646
Author: Austin McDaniel <amcdaniel2@gmail.com>
Date:   Fri Sep 9 17:35:34 2016 -0400

    (release): 0.4.0

commit aba0763c0540bfce37160949191be21847c7e9a8
Author: Austin McDaniel <amcdaniel2@gmail.com>
Date:   Fri Sep 9 17:34:48 2016 -0400

    (chore): some more updates

PS C:\Users\guomingz\angular2-data-table> git pull
remote: Counting objects: 178, done.
remote: Compressing objects: 100% (161/161), done.
Receiving objects:  91% (162/178)   d 19 (delta 16), pack-reused 0 eceiving objects:  90% (161/178)
Receiving objects: 100% (178/178), 88.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (102/102), completed with 14 local objects.
From https://github.com/swimlane/angular2-data-table
   ff23835..4e44be6  master     -> origin/master
 * [new tag]         0.6.0      -> 0.6.0
 * [new tag]         0.5.0      -> 0.5.0
 * [new tag]         0.5.1      -> 0.5.1
 * [new tag]         0.5.2      -> 0.5.2
Updating ff23835..4e44be6
Fast-forward
 README.md                                   |  2 +-
 docs/README.md                              |  3 +-
 docs/SUMMARY.md                             |  1 +
 docs/changelog.md                           | 13 ++++++
 docs/credits.md                             |  1 -
 docs/introduction/installing.md             |  2 +-
 package.json                                | 38 ++++++++---------
 release/angular2-data-table.cjs.js          | 33 ++++++++++-----
 release/angular2-data-table.cjs.js.map      |  2 +-
 release/angular2-data-table.es.js           | 35 +++++++++++-----
 release/angular2-data-table.es.js.map       |  2 +-
 release/angular2-data-table.js              | 14 ++++---
 release/angular2-data-table.js.map          |  2 +-
 release/angular2-data-table.min.js          |  2 +-
 release/angular2-data-table.min.js.map      |  2 +-
 release/angular2-data-table.umd.js          | 33 ++++++++++-----
 release/angular2-data-table.umd.js.map      |  2 +-
 release/components/DataTable.js             | 23 ++++++++++-
 release/components/DataTable.js.map         |  2 +-
 release/components/DataTableColumn.js       |  9 ++++
 release/components/DataTableColumn.js.map   |  2 +-
 release/components/body/Body.d.ts           |  2 +-
 release/components/body/Body.js             | 13 +++++-
 release/components/body/Body.js.map         |  2 +-
 release/components/body/BodyCell.js         |  9 ++++
 release/components/body/BodyCell.js.map     |  2 +-
 release/components/body/BodyRow.js          |  9 ++++
 release/components/body/BodyRow.js.map      |  2 +-
 release/components/body/ProgressBar.js      |  9 ++++
 release/components/body/ProgressBar.js.map  |  2 +-
 release/components/footer/Footer.js         |  9 ++++
 release/components/footer/Footer.js.map     |  2 +-
 release/components/footer/Pager.js          |  9 ++++
 release/components/footer/Pager.js.map      |  2 +-
 release/components/header/Header.js         |  9 ++++
 release/components/header/Header.js.map     |  2 +-
 release/components/header/HeaderCell.js     |  9 ++++
 release/components/header/HeaderCell.js.map |  2 +-
 release/directives/Draggable.js             |  9 ++++
 release/directives/Draggable.js.map         |  2 +-
 release/directives/LongPress.js             |  9 ++++
 release/directives/LongPress.js.map         |  2 +-
 release/directives/Orderable.js             |  9 ++++
 release/directives/Orderable.js.map         |  2 +-
 release/directives/Resizeable.js            |  9 ++++
 release/directives/Resizeable.js.map        |  2 +-
 release/directives/Scroller.d.ts            |  1 +
 release/directives/Scroller.js              | 18 +++++++-
 release/directives/Scroller.js.map          |  2 +-
 release/directives/TemplateWrapper.js       |  9 ++++
 release/directives/TemplateWrapper.js.map   |  2 +-
 release/directives/Visibility.js            |  9 ++++
 release/directives/Visibility.js.map        |  2 +-
 release/services/State.d.ts                 |  6 +--
 release/services/State.js                   |  9 ++++
 release/services/State.js.map               |  2 +-
 src/angular2-data-table.ts                  |  6 ---
 src/components/DataTable.ts                 | 14 +++++--
 src/components/body/Body.ts                 | 11 ++---
 src/demos/module.ts                         |  3 +-
 src/demos/multiple.ts                       | 64 +++++++++++++++++++++++++++++
 src/directives/Scroller.ts                  |  5 ++-
 src/polyfills.ts                            |  3 +-
 src/services/State.ts                       | 15 +++----
 tsconfig.json                               |  2 +-
 65 files changed, 425 insertions(+), 119 deletions(-)
 create mode 100644 docs/changelog.md
 create mode 100644 src/demos/multiple.ts
PS C:\Users\guomingz\angular2-data-table> git log
commit 4e44be6915cc10fc1445cdef301927ac5ad860bf
Author: Austin McDaniel <amcdaniel2@gmail.com>
Date:   Fri Sep 16 08:29:41 2016 -0400

    (release): 0.6.0

commit 63b63506ddff217c0719cb1afe7dcc60c156dfe8
Author: Austin McDaniel <amcdaniel2@gmail.com>
Date:   Fri Sep 16 08:28:25 2016 -0400

    (docs): update docs for 2.0.0 release

commit 6d39e9c6246ce589d394596e66d61d7366b37a58
Merge: 27bc3a8 93f7e4c
Author: Austin <amcdaniel2@gmail.com>
Date:   Fri Sep 16 08:24:16 2016 -0400

    Merge pull request #129 from Tempus35/master

    Fix horizontal header issue

commit 27bc3a82d7168fa56a93d8b1082c9bd1955f0cd3
Merge: f8ff16b 044f994
Author: Austin <amcdaniel2@gmail.com>
Date:   Fri Sep 16 08:23:37 2016 -0400

    Merge pull request #126 from ocombe/patch-3

    update to angular 2.0.0 & typescript 2.0.2
PS C:\Users\guomingz\angular2-data-table> npm start

> angular2-data-table@0.6.0 start C:\Users\guomingz\angular2-data-table
> webpack-dev-server

C:\Users\guomingz\angular2-data-table\webpack.config.js:17
function webpackConfig(options = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\guomingz\angular2-data-table\node_modules\webpack\bin\convert-argv.js:93:13)
    at Object.<anonymous> (C:\Users\guomingz\angular2-data-table\node_modules\webpack-dev-server\bin\webpack-dev-server.js:127:48)
    at Module._compile (module.js:409:26)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\guomingz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.6.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-data-table@0.6.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\guomingz\angular2-data-table\npm-debug.log

PS C:\Users\guomingz\angular2-data-table>

**Comment by amcdnl** [comment]
Ah, gotta be on Node 5+
