### ISSUE TITLE
Columns are not updated on options value change

### ISSUE THREAD

**Issue by shedar** [swimlane/angular2-data-table#119]
Demo:
https://plnkr.co/edit/3ULqP4DGIc1YzBu0bDyS?p=preview

Click first button (sets options with columns "name","value"), then second button (sets options with columns "label","value")

Expected behavior: new set of columns shown.

Current behavior: same set of columns show, only columns with matched property names have values.

Use case: displaying of dynamic reports (set of columns is defined by server response)

**Comment by amcdnl** [comment]
Your changing your whole config which is de-referencing properties. You need to slice out of the existing array like my example does.

**Comment by shedar** [comment]
Thanks for response. I tried to splice/push columns. It shows a new set of columns, but width of columns becomes wrong after switch.

Before switch (set1)

![image](https://cloud.githubusercontent.com/assets/477298/18508239/1328f05e-7a7c-11e6-89d4-70ddb0980cca.png)

After switch (set2): 

![image](https://cloud.githubusercontent.com/assets/477298/18508251/1fbef53e-7a7c-11e6-880b-e35facd3e3ea.png)

Here is an updated plunker https://plnkr.co/edit/IiRcv2izpaV5bhmPmCvq?p=preview

**Comment by amcdnl** [comment]
Interesting, so columns are not being redistrubuted after a re-apply.

**Comment by shedar** [comment]
Not sure if this one is related or I should create a new issue.
When I change rows and columns, in some cases I get obsolete rows

https://plnkr.co/edit/PuZzxg4jvm28UgKCtI5f?p=preview

Steps to reproduce:

1. set1 - 2 columns, 2 data rows (ok)
2. set2 - 3 columns, 6 data rows (ok)
3. set1 - 2 columns, 4 data rows, two of them are from previous rows (bugged)

I tried to replace rows array and to splice/push - result is the same.

P.S. you marked issue as a bug, but didn't reopen it.

**Comment by stofte** [comment]
Instead of creating a new issue, I'll chime in here and say I'm also seeing this issue, since I'm trying to do dynamic columns, but updating it after init does not do anything. Sample:  https://plnkr.co/edit/DAuKfBV0AMKapleU5YmK

**Comment by java2kus** [comment]
@stofte - There is an issue in the code where you were pushing to `this.columns` instead of `this.options.columns`.  Correct code below:

```
[
        new TableColumn({ prop: 'name' }),
        new TableColumn({ name: 'Gender' }),
        new TableColumn({ name: 'Company' })
      ].forEach(col => {
       this.options.columns.push(col);
      })   
```

**Comment by stofte** [comment]
@java2kus  Thanks for correcting that! 👍

**Comment by smorcuend** [comment]
@stofte @java2kus I have updated the code according new version >=1.0.0
The component seems works perfectly.
Sample: https://plnkr.co/edit/20wOK7cvwhwDhNYMYeQr
