### ISSUE TITLE
no depend from jspm

### ISSUE THREAD

**Issue by kanipowa** [swimlane/angular2-data-table#12]
If you want to use angular2 data-table you install jspm.
Is there any workaround to use data-table witouth installing jspm?

**Comment by DzmitryShylovich** [comment]
U can reference compiled classes in your index.html directly from github release folder using https://rawgit.com/

**Comment by amcdnl** [comment]
@kanipowa JSPM is a dev dependency for building. You only need it if you are developing on the project locally.

**Comment by DzmitryShylovich** [comment]
We need jspm to install data table via npm :(
I think u should update [docs](https://github.com/swimlane/angular2-data-table/blob/master/docs/introduction/installing.md#installing) to reflect this fact.

**Comment by amcdnl** [comment]
Oh I see what you mean...Maybe we can make it reference the local install of jspm vs global.

Re-opening to address this.

**Comment by amcdnl** [comment]
@DzmitryShylovich see if my last commit works for you.

**Comment by tamascsaba** [comment]
@amcdnl thx :+1: 
Only one thing pls release to npm

**Comment by amcdnl** [comment]
Done!
