### ISSUE TITLE
demos not working...

### ISSUE THREAD

**Issue by born2net** [swimlane/angular2-data-table#120]
demos not working...
please fix in docs

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by vefimov** [comment]
Same for me

**Comment by amcdnl** [comment]
Ya, plunkr didn't take my changes. I'll resolve today.

**Comment by frusciante** [comment]
where can we find the working example code in this meanwhile?

**Comment by PerfectPixel** [comment]
Until the plunkrs are updated you can open the plunkr and change the version of zone.js in the **index.html** from `zone.js@0.6.12` to `zone.js@0.6.23`.

Then the plunkr should work again.

**Comment by amcdnl** [comment]
Fixed! :)
