### ISSUE TITLE
table not take 100% of conatiner and stay 900px

### ISSUE THREAD

**Issue by penso89** [swimlane/angular2-data-table#124]
the table not take all the width of the conainer.

![untitled](https://cloud.githubusercontent.com/assets/8013826/18526317/c55f729c-7ac8-11e6-93b5-4c546d359dd8.png)
 

 this.options = new TableOptions({
            columnMode: ColumnMode.standard,
            headerHeight: 50,
            rowHeight: 'auto',
            columns: [
                new TableColumn({ name: 'Id', prop: 'id'}),
                new TableColumn({ name: 'Name', prop: 'name', template: this.nameLink }),
                new TableColumn({ name: 'Company', prop: 'company_id' }),
                new TableColumn({ name: 'Description', prop: 'description' }),
                new TableColumn({ name: 'Created at', prop: 'created_at' }),
                new TableColumn({ name: 'Created by', prop: 'created_by' })
            ]

**Comment by amcdnl** [comment]
Please make a demo reproducing the error.

**Comment by penso89** [comment]
The error are not related to the component..
There is a reason why it's not taking all the width.
From the picture you can see that the container is bigger than the table

**Comment by amcdnl** [comment]
Ok, a demo in plunkr might make it easier for me to help.

**Comment by penso89** [comment]
Tnx it's fixed...
