### ISSUE TITLE
[BUG] Inner Body behind table

### ISSUE THREAD

**Issue by Tempus35** [swimlane/angular2-data-table#128]
http://imgur.com/a/QbObF

As you can see in the image the select is behind he footer, instead of being on top of it and it is adding to the scroll bar though it should not.

**Comment by amcdnl** [comment]
@Tempus35 Can you make a demo?

**Comment by Tempus35** [comment]
So figured out a way to fix this, both .datatable and .datatable-body need overflow: visible on them.

**Comment by amcdnl** [comment]
Per our discussion in Gitter:

>  the page has overflow scrolling for obvious reasons, however, if u have a date picked dropdown that is gonna be appended as a sibling therefore adhereing to the same overflow laws. There most cases u would have ur dropdown append the content into the body to have proper layout. U need to ensure the picker is appended to the body in this situation.

@Tempus35 - can you reference the project you are using for that?

**Comment by Tempus35** [comment]
The project for the datapicker? [http://materializecss.com/about.html](http://materializecss.com/about.html) via [https://github.com/InfomediaLtd/angular2-materialize](https://github.com/InfomediaLtd/angular2-materialize) which is because Material2 is not finished. I have no clue on how the datepicker is attach to the DOM it uses materialize="pickadate" as a directive to make it a datapicker.

**Comment by amcdnl** [comment]
Closing as this is un-related to the table.
