### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by DzmitryShylovich** [swimlane/angular2-data-table#13]
TypeScript needs typings for external librairies. So it would be great if you could add the typings to the DefinitelyTyped repository, or better, within the NPM module (as recent TypeScript compilers can pick it up automatically).

**Comment by amcdnl** [comment]
Ah, so I need to generate the types in the release probably? Any suggestions on best approach for this?

**Comment by DzmitryShylovich** [comment]
I guess u can use use the `--declaration` command-line switch as described [here](http://stackoverflow.com/a/12695001).

**Comment by amcdnl** [comment]
Added flag in config, need to do more testing but its a start. https://github.com/swimlane/angular2-data-table/commit/0425abd8ce8d2be4fec6e975af470f641c274272

**Comment by kanipowa** [comment]
@amcdnl can you publish a release with a typing definitions (d.ts, which are currently missing from release folder)?

**Comment by tamascsaba** [comment]
I use typescript and import {DataTable} from 'angular2-data-table' throw error, because typing definition is missing for module.

**Comment by amcdnl** [comment]
Hmm, not sure the best way to build those into a single file since they are on a file by file basis. 

Perhaps have TS do the build in one file instead of JSPM?

**Comment by tamascsaba** [comment]
With ```tsc``` you can build all files separately or build to one single bundle. I think comonjs the best module system, because you can use with webpack, broswerify and with systemjs too.

tsconfig.json
```
{
   compilerOptions: {
    "module": "commonjs",
    "outFile": "release/bundle.js",
  }
}
```
or
```
{
  compilerOptions: {
    "module": "commonjs",
    "outDir": "lib"
  }
}
```

**Comment by amcdnl** [comment]
@tamascsaba Thanks for the feedback! I'm planning to move to webpack soon and hopefully can get these resolved by that. JSPM + TS don't really work that well together.

**Comment by tamascsaba** [comment]
Hy I will add a P.M soon as possible :)

**Comment by amcdnl** [comment]
Should be fixed now. :)
