### ISSUE TITLE
Column And Global Search Feature

### ISSUE THREAD

**Issue by shivarajnaidu** [swimlane/angular2-data-table#131]
It is very needy to have search in terms of globally and by column in data tables...
For client side and server side process..
Please consider feature set present in this Angular 1 data tables projects features as minimum feature set needed for data tables...
[https://github.com/l-lin/angular-datatables](https://github.com/l-lin/angular-datatables)

Thank You !

**Comment by amcdnl** [comment]
Out of scope for this project. Please see: https://swimlane.gitbooks.io/angular2-data-table/content/introduction/architecture.html

**Comment by shivarajnaidu** [comment]
Thanks For Kind Response

**Comment by ShinDarth** [comment]
> There is a demo for how to do filtering of your data here: https://swimlane.gitbooks.io/angular2-data-table/content/examples/filtering.html
 page not found

**Comment by mrsan22** [comment]
Correct Link: https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/filter.component.ts

**Comment by pradeepmay13** [comment]
anybody tell me how we filter data based on multiple columns in swimlane filter
