### ISSUE TITLE
Feature: External change to selection

### ISSUE THREAD

**Issue by fridolin-koch** [swimlane/angular2-data-table#132]
We are trying to unset the selection of the table, but had no success. After digging through the code we found a solution using `OnChanges`. See this commit: https://github.com/fridolin-koch/angular2-data-table/commit/96c8dd981420dde73dd6d2ab3273fa69fa5442b2

**Expected Behavior:**

Clicking on "Reset" unsets the selection of the table

Working version using my fork: https://plnkr.co/edit/V8OGXHKIq65eV0g27gW1?p=preview

**Actual Behavior:** 

Rows are still selected: https://plnkr.co/edit/Sbeb7ps5MaLipal9xoMQ?p=preview

**Comment by jtomaszewski** [comment]
Maybe be should move all those bindings like `setRows` `setOptions` `setSelected` from `ngOnInit` to `ngOnChanges`? See https://github.com/jtomaszewski/angular2-data-table/commit/4fca92f1e353dbca57989f7763c2e93f9b192e6d .

**Comment by amcdnl** [comment]
Ya, thats looks fine! PR and I'll accept.
