### ISSUE TITLE
Page limit is not applied if rows are set initially

### ISSUE THREAD

**Issue by shedar** [swimlane/angular2-data-table#133]
Demo https://plnkr.co/edit/4cZiytxsCH4xz8jsotxy?p=preview

Limit is set to 3, but initial render renders all rows:

![image](https://cloud.githubusercontent.com/assets/477298/18628654/e5868f66-7e69-11e6-93a6-e7908ed0e171.png)

Calling `updateRows()` in `DataTableBody.ngOnInit` should fix it if I understand the reason of the bug correctly

**Comment by amcdnl** [comment]
Fixed in 0.7.4
