### ISSUE TITLE
Expressive HeaderTemplate

### ISSUE THREAD

**Issue by MonicaOlejniczak** [swimlane/angular2-data-table#134]
It doesn't look like a header template attribute can be specified on a `<datatable-column>` component? An example can be seen here:

```
<datatable-column name="Gender" [headerTemplate]="hdrTpl">
     <template let-row="row" let-value="value" let-i="index">
         ....
    </template>
</datatable-column>
```

Which results in `Can't bind to 'headerTemplate' since it isn't a known property of 'datatable-column'.`.

Additionally, there doesn't seem to be a way to specify the header template as an inline template. For example:

```
<datatable-column name="Gender">
     <header-template>...</header-template>
     <template let-row="row" let-value="value" let-i="index">
         ....
    </template>
</datatable-column>
```

[Here's a plunker demonstrating the issue.](https://plnkr.co/edit/cHVrwxgny9D0r3ytfR4E?p=preview)

**Comment by amcdnl** [comment]
This is a great suggestion, I should be able to do this pretty easy.

**Comment by ashleahhill** [comment]
Currently, if you provide two templates the first is treated as header. There are some issues with it though.

https://github.com/swimlane/angular2-data-table/blob/master/src/components/datatable-column.directive.ts

**Comment by amcdnl** [comment]
@ashleahhill - Yes, thats correct. Whats the issue? Forgot to close this :)

**Comment by ashleahhill** [comment]
@amcdnl 
I couldn't get sort to work with the header template. However, I think its related to the sort function not supporting deep values, since a shallow value works fine.

**Comment by inigay** [comment]
Inputting two templates in datatable-column doesn't work

**Comment by amcdnl** [comment]
See: https://plnkr.co/edit/iH1e7cIAdX5Ds4jY7WYc

**Comment by inigay** [comment]
Thanks, I used version for rc5, one for 2.0 works fine. Although, when I put a custom template for the header it doesn't sort after that. Is it possible to have both?
