### ISSUE TITLE
column-based filtering

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#135]
PRPOSITION:
Does it envisageable add filter input under each column ? A litle like http://i.imgur.com/ERUHmza.png

**Comment by amcdnl** [comment]
You could do this with a header template and then just filtering the rows via normally but only including that in your function.

We tend to shy away from implementing these type of features since they are pretty specific to your business use case how you want to present filtering, the options that you want to allow and controls to do which additionally how to filter ( client or server ).

Instead I think a demo of how to accomplish this would be better than a core feature.

**Comment by istiti** [comment]
@amcdnl first thanks. Please apologize In documentation I do not have example of headerTemplate, the tools is very nice but doc site is poor,  when I type in input search doc: noresult! 

I have to try each example to find this ? Or do you have some plunker example thanks

**Comment by amcdnl** [comment]
No problem! The doc is not our library and ya I agree the search is pretty hit and miss.

I just realized there is no demo up on the docs, here is a demo in the code tho - https://github.com/swimlane/angular2-data-table/blob/master/src/demos/template.ts#L22

**Comment by istiti** [comment]
@amcdnl please apologize I try to apply what you say but no successs (I catch against solution since 6days) I think the demo page aren't very expressives could you get a look to my plunker http://plnkr.co/edit/fFGt2X6h1ZN8TfSuEi6K?p=preview

Juste click on button "Get data1" and you will see the first column header isn't replaced by input, I tried tempalte solution ... just switch between component.ts and component.html, thanks a lot!

**Comment by touqeershafi** [comment]
@istiti if you can do a good plunker on this that will be very help full for the community.

**Comment by kevinding0218** [comment]
I am also looking forward a stable and dynamic column filter as expected!

**Comment by francisminu** [comment]
Please find a working plunker here:
https://plnkr.co/edit/2F1Jol1i9BsYYWNat42V

**Comment by francisminu** [comment]
For some weird reason, my plunks are not running as expected. Please try the below:
.HTML file:
<ngx-datatable
        #myTable
        class='material'
        [rows]='createdTicketRows'
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        [rowHeight]="30"
        >
        <ngx-datatable-column prop="PropertyName" width="10">
        <ngx-datatable-column prop="PropertyName" [minWidth]="200" height="100">
            <ng-template let-column="column" height="100" ngx-datatable-header-template >
                <label style="height:10px;cursor:pointer">PropertyName</label><br/>
                  <input
                    type='text'
                    id="PropertyName"
                    style='width:100%;height:30px;border:1px;'
                    placeholder='Filter..'
                    (keyup)='FilterData($event)'
                  />
                </ng-template>
        </ngx-datatable-column>
      </ngx-datatable>

.TS file:
@ViewChild(DatatableComponent) myTable: DatatableComponent;
tempData = actualData;

FilterData(event) {
			let columnName = event.currentTarget.id;
			const val = event.target.value.toLowerCase();
			const filteredData = this.tempData.filter(function(d) {
				return d[columnName].toLowerCase().indexOf(val) !== -1 || !val;
			});
			this.actualData= filteredData;
			this.myTable.offset = 0;
  }

Let me know if this works.

**Comment by danielehrhardt** [comment]
Is it now in Scope?
