### ISSUE TITLE
systemjs builder bundle not working on data table

### ISSUE THREAD

**Issue by penso89** [swimlane/angular2-data-table#137]
hi,
without bundle the table working perfect but after it's crush.
grunt task is making the bundle (grunt-system-js-builder)
i think its a inside component,

![image](https://cloud.githubusercontent.com/assets/8013826/18718413/111dceaa-802c-11e6-97d3-90bcc91140cd.png)

tnx for help

**Comment by amcdnl** [comment]
Can you make a github repository repo for this. Without that I can't test.

**Comment by amcdnl** [comment]
Closing due to no response.
