### ISSUE TITLE
Move examples from plunker to local repo

### ISSUE THREAD

**Issue by jtomaszewski** [swimlane/angular2-data-table#148]
Plunker since yesterday raises quite a lot of connection errors and I need to refresh the example's page to see it correctly.

Besides, it propably would be easier to maintain them, if they would be in the local repository and always used the current angular & angular2-data-table's version.

**Comment by luisfarfan** [comment]
![image](https://cloud.githubusercontent.com/assets/10887366/18869189/d8481560-8470-11e6-8c9c-b913f44f6fca.png)

My internet its ok, i can navigate other pages. I try too in anonymous.

**Comment by jeffconklin** [comment]
I can view the pages/examples, but I receive an error. Example:

https://swimlane.gitbooks.io/angular2-data-table/content/examples/client-paging.html

"SyntaxError: invalid property id"...
![screenshot from 2016-09-27 10 16 01](https://cloud.githubusercontent.com/assets/6152325/18877493/70cadf28-849b-11e6-8c9e-3961404b5944.png)

When viewing on plunker directly (https://plnkr.co/edit/cu3cId3n4IUH7sNydxoW?p=preview) I first received the same error. Once I refreshed the page the error went away: 
![screenshot from 2016-09-27 10 20 44](https://cloud.githubusercontent.com/assets/6152325/18877720/12c2ff2c-849c-11e6-8834-1ebba7aa3f8f.png)

**Comment by amcdnl** [comment]
I did them in plunkr's so it was easy for people to tweak them and use them for test cases. I'm down for building an official demo page though. PR? ;)

**Comment by deeg** [comment]
@amcdnl, looks like this can be closed now.

It does make it a bit harder for a user to get a basic demo plunker up and running. Might want to consider adding a link to a plunker on one of the .md pages.
