### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by jtomaszewski** [swimlane/angular2-data-table#149]
Is the angular2-data-table optimized when it comes to performance?

I didn't get to see through all the code, but after a quick glimpse:
- we could add a `trackBy` option to `*ngFor="let row of rows; let i = index;"` in `Body` component's template
- components like `BodyCell`, `BodyRow` should propably be dependant only on Inputs and use `ChangeDetectionStrategy.OnPush`
- components like `Body` propably could also use `ChangeDetectionStrategy.OnPush`, but as it's currently heavily dependant on `StateService`, we would need to add some rxjs observables to that or something.

What do you guys think? Maybe I could help a bit with that.

**Comment by amcdnl** [comment]
@jtomaszewski - Actually, I tried some of those ....

1. trackBy gave me some odd errors when i tried it rc1, worth re-looking at for sure. You can track by the column id defined [https://github.com/swimlane/angular2-data-table/blob/master/src/models/TableColumn.ts#L23](here).
2. I had those changed, however, that caused errors with things not updating correctly. See this [https://github.com/swimlane/angular2-data-table/commit/4c0658dff6b4cf6d9b040f5c3cc56b929911f27f#diff-6c5fe72c2cab8659bc1ddbfa686ed2f9](commit).
3. Absolutely. I've already got an issue open for [https://github.com/swimlane/angular2-data-table/issues/32](rxjs) support. I'd love to work with you on implementing that, my rx is not to the standard something like this requires.

**Comment by jtomaszewski** [comment]
Hey, why did you close it? ;] 

There's still some commits here that can be merged:
- https://github.com/jtomaszewski/angular2-data-table/commit/8658afe39b440b9583c5537954e1778475f12a21
- https://github.com/jtomaszewski/angular2-data-table/commit/9b87bef41492a470c467be6c92e211e97f33bda3
- https://github.com/jtomaszewski/angular2-data-table/commit/b63bc30de4d6c5578371e212b4cb3acccfaaa86d
- https://github.com/jtomaszewski/angular2-data-table/commit/16d2652d5036ee770924ef998c2e0b631f11e4a6

Should I do sepearte PRs for all of them?

**Comment by amcdnl** [comment]
SorryI thought you said it was closed. I will manually merge them in :)

**Comment by amcdnl** [comment]
The do check has to stay but I did the rest :)

**Comment by jtomaszewski** [comment]
Thanks for the quick merging ;) 

Why does the doCheck has to stay? It's tempting to get rid of it as well.

**Comment by amcdnl** [comment]
Its for when the columns change externally ( i think lol ) and one other thing I forgot. I will dig it up though and add comments.

**Comment by amcdnl** [comment]
Closing as no longer relevant due to total onpush refactor.
