### ISSUE TITLE
documentation and demos is down!

### ISSUE THREAD

**Issue by luisfarfan** [swimlane/angular2-data-table#150]
documentation and demos is down!
https://swimlane.gitbooks.io/angular2-data-table/content/

**Comment by jtomaszewski** [comment]
Screen? Documentation works for me.

About the demos, plunker issues connection error a lot and they work after a couple of F5 refresh ( https://github.com/swimlane/angular2-data-table/issues/148 ).

**Comment by amcdnl** [comment]
Work fine for me, sometimes the plunkrs get aggressive w/ caching.
