### ISSUE TITLE
click on datatable-body-cell

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#161]
ENHANCEMENT:
actually it isn't possible to click on <datatable-body-cell> we can add inside <template> a (click) event binding but height od my DIV is litle than <datatable-body-cell> because this have padding or so and I can't click to it

Does it envisageable add click inside whole <datatable-body-cell> tag

**Comment by amcdnl** [comment]
You can remove the padding added by default by the CSS and add that padding to your div. https://github.com/swimlane/angular2-data-table/blob/master/src/themes/material.scss#L87
