### ISSUE TITLE
BUG when set width to <datatable-column>

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#162]
BUG:
1. I use virtual scroll
2. I use `columnMode: ColumnMode.standard,`
3. I set  `<datatable-column ... width="300">`

RESULT:
1. My column have really width 300px but I have an scrollbar horizontal  of` 33554400px `!!!!
2. GIF:
![datatable-width-column](https://cloud.githubusercontent.com/assets/2789203/18956985/b739c582-865d-11e6-88b7-db4e7df0273b.gif)

**Comment by amcdnl** [comment]
LOL - Good find. Will get that fixed.

**Comment by amcdnl** [comment]
Can you make a demo case? I wasn't able to repo this.

**Comment by amiller29au** [comment]
My pull request #143 fixes this issue.

**Comment by istiti** [comment]
@amiller29au does you version merged with 0.7.4 ? because I have always same problem

**Comment by istiti** [comment]
@amcdnl yes I just edited my last demo here you can see hrizontal scrollbar of width 33554400px LOL 
http://plnkr.co/edit/CQ3vqMhf3dJACEP3bDF3?p=preview

**Comment by amiller29au** [comment]
@istiti - not yet

**Comment by istiti** [comment]
@amiller29au if I get your changes Do i need build project or?

**Comment by amiller29au** [comment]
@istiti - yes you will need to do a release build again

**Comment by amiller29au** [comment]
PR - #167
