### ISSUE TITLE
Column templates aren't working

### ISSUE THREAD

**Issue by PatrickHuetter** [swimlane/angular2-data-table#169]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

The column renders the value and not the value within the template.

**Expected behavior**

The rendered value within the given template.

**Reproduction of the problem**
It's also not working on the examples page: https://swimlane.gitbooks.io/angular2-data-table/content/examples/templates.html The images are missing.

![bildschirmfoto 2016-10-01 um 16 00 08](https://cloud.githubusercontent.com/assets/1142911/19014553/8b35f8a4-87f0-11e6-8f88-52e93c2de26c.png)

I'm using angular 2.0 final and webpack.

UPDATE: Got it working in plunker, using "cellTemplate" as configuration key instead of "template". But can't get it working in my local project. My cellTemplate never gets used.

**Comment by PatrickHuetter** [comment]
Got it working in my project. I had to initialize the columns after view initialization because before the reference to the ViewChild wasn't initialized.

```
  ngAfterViewInit() {
    this.initDataTableColumns();
    this.page();
  }

  initDataTableColumns() {
    this.options.columns = [
      new TableColumn({cellTemplate: this.productImageTmpl, name: 'Image', prop: 'imageUrl'}), ...
    ];
  }
```

**Comment by amcdnl** [comment]
Fixed Docs too
