### ISSUE TITLE
Unable to load data-table via system.config.ts.

### ISSUE THREAD

**Issue by Xamlware** [swimlane/angular2-data-table#174]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

404 Not found error when loading datatable

**Expected behavior**

Datatable loads without error.

**Reproduction of the problem**

I'm trying to load the datatable via system.config.ts.  I added the datatable to it as I have done with all the other 3rd party modules and have had problems with it since day one.  It is probably my misuse or misunderstanding of what needs to be done to load it.
`
"use strict";

// SystemJS configuration file, see links for more information
// https://github.com/systemjs/systemjs
// https://github.com/systemjs/systemjs/blob/master/docs/config-api.md

/***********************************************************************************************
- User Configuration.
  *******************************************************************************************_**/
  /_\* Map relative paths to URLs. */
  const map: any = {
  'primeng': 'vendor/primeng',
  'angular2-data-table': 'vendor/angular2-data-table',
  'moment': 'vendor/moment/moment.js',
  '@angular/core': 'vendor/@angular/core/bundles/core.umd.js',
  '@angular/common': 'vendor/@angular/common/bundles/common.umd.js',
  '@angular/compiler': 'vendor/@angular/compiler/bundles/compiler.umd.js',
  '@angular/platform-browser': 'vendor/@angular/platform-browser/bundles/platform-browser.umd.js',
  '@angular/platform-browser-dynamic': 'vendor/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
  '@angular/http': 'vendor/@angular/http/bundles/http.umd.js',
  '@angular/router': 'vendor/@angular/router/bundles/router.umd.js',
  '@angular/forms': 'vendor/@angular/forms/bundles/forms.umd.js',
  
  // angular testing umd bundles
  '@angular/core/testing': 'vendor/@angular/core/bundles/core-testing.umd.js',
  '@angular/common/testing': 'vendor/@angular/common/bundles/common-testing.umd.js',
  '@angular/compiler/testing': 'vendor/@angular/compiler/bundles/compiler-testing.umd.js',
  '@angular/platform-browser/testing': 'vendor/@angular/platform-browser/bundles/platform-browser-testing.umd.js',
  '@angular/platform-browser-dynamic/testing': 'vendor/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
  '@angular/http/testing': 'vendor/@angular/http/bundles/http-testing.umd.js',
  '@angular/router/testing': 'vendor/@angular/router/bundles/router-testing.umd.js',
  '@angular/forms/testing': 'vendor/@angular/forms/bundles/forms-testing.umd.js',
  
  // other libraries
  'rxjs': 'vendor/rxjs',
  'angular2-in-memory-web-api': 'vendor/angular2-in-memory-web-api',
  'guid': 'vendor/guid/guid.js',
  };

/*\* User packages configuration. */
const packages: any = {
  'primeng': { defaultExtension: 'js' },
  'angular2-data-table': { defaultExtension: 'js' },
  'moment': { format: 'cjs' },
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
- Everything underneath this line is managed by the CLI.
  **********************************************************************************************/
  const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/forms',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  
  // Thirdparty barrels.
  'rxjs',
  // App specific barrels.
  'app',
  'app/shared',
  'app/home/login/change',
  'app/home/login/forgot',
  'app/home/login/forgot-verify',
  'app/home/login/challenge',
  'app/logout',
  'app/food/settings',
  'app/food/diary/add',
  /*\* @cli-barrel */
  ];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/*\* Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });

`

**What is the motivation / use case for changing the behavior?**

I would like to use it.

**Please tell us about your environment:**

Win10, angular 2.0.0, angular-cli.1.0.0.beta-10, VS Code
- **Table version:** 0.7.x
  
  
  
  Tried to load the latest npm package.
- **Angular version:** 2.0.x
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  IE11 and IE Edge
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  typescript 2.0.2

**Comment by amcdnl** [comment]
Please make a demo git repo.

**Comment by Xamlware** [comment]
I don't even know what that is.  All I'm asking for is a sample system.config showing how to load the angular2-data-table.

**Comment by Xamlware** [comment]
Okay. Repo here: Xamlware/Angular2-Data-Table-Repo

**Comment by padryn** [comment]
I get the same 404 error when trying to use data-table, though I have a slightly different setup.  The setup is pretty much the basic demo as described in the angular2 docs.  So in the systemjs.config.js file. 

`(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                             'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'rxjs':                             'node_modules/rxjs',
    'angular2-data-table':        'node_modules/angular2-data-table'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-data-table':         {defaultExtension: 'js' }
  };`

If I replace the location of angular2-data-table with the unpkg url, the 404 goes away.  But we can't deploy the application to production using an external library.

**Comment by amcdnl** [comment]
Take a look at the plunkr, they are using systemjs.

**Comment by padryn** [comment]
Thank you for the response.  I've looked at several of the examples and the config.js file for each of the examples.  They all seem to reference https://unpkg.com/angular2-data-table.  I didn't see any examples on how to import the package locally (i.e. a copy of the component that's been 'installed' locally via npm install).

And apologies if I'm missing something obvious, I'm much more of a back-end Java guy.
