### ISSUE TITLE
DataTable component should be exported from Angular2DataTableModule

### ISSUE THREAD

**Issue by tscislo** [swimlane/angular2-data-table#176]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
It's not possible to get reference to DataTable from parent component using @ViewChild
For example:

```
  @ViewChild(DataTable)
  dataTable:DataTable
```

**Expected behavior**
It should be possible to get reference to DataTable component from parent component

**Reproduction of the problem**
https://plnkr.co/edit/Bdcvm6P7xIvHFpM3FLqD?p=preview

**What is the motivation / use case for changing the behavior?**
It's allows to get full access to component's API from parent component.

* **Table version:** 
0.8.0

* **Angular version:** 
2.0.0

* **Language:**
TypeScript

**Comment by amcdnl** [comment]
Fixed in 0.9.1
