### ISSUE TITLE
Default sort doesn't work with "deep" properties

### ISSUE THREAD

**Issue by ashleahhill** [swimlane/angular2-data-table#181]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When you specify a "deep" property as the `prop` for a column: 

```typescript
new TableColumn({
    name: 'Cylinders',
    prop: 'engine.cylinders'
}),
```

or 

```html
            <datatable-column name="Cylinders" prop="engine.cylinders">
              <template let-value="value">
                {{value}}
              </template>
            </datatable-column>
```

Sort malfunctions, the entire data set is not sorted.

**Expected behavior**
All rows are sorted based on the value for the column. This is the behavior for rows that use a "shallow" property

**Reproduction of the problem**
http://plnkr.co/edit/9Eug63qi775HVCMe3BhO?p=preview

1. On either the "Expressive: Cars" tab or the "Templated: Cars" tab, try to sort by Formation
2. See that the sort does not work.
3. On either the "Expressive: Cars" tab or the "Templated: Cars" tab, try to sort by Color
4. See the the sort does work

**What is the motivation / use case for changing the behavior?**
I need to sort on deep properties, 

Since its trivial (from the usage standpoint) to display these properties using the `prop` input, it seems like sorting by them should be supported by the default sort 

**Please tell us about your environment:**
Windows
VSCode
Node
Webpack Dev Server

* **Table version:** 0.7.x
0.9.2

* **Angular version:** 2.0.x
@angular/core@2.0.1

* **Browser:**
Only tried in Chrome

* **Language:** 

TypeScript@2.0.3

**Comment by amcdnl** [comment]
We probably just need to apply similar code as this does - https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/body-cell.component.ts#L34 ... Can you PR that?

**Comment by ashleahhill** [comment]
@amcdnl,
Submitted
