### ISSUE TITLE
error AoT compilation with angular-cli  Unexpected value 'Angular2DataTableModule' imported by the module

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#184]
I tried `ng build --prod --aot` 
I get:
`0% compiling Unexpected value 'Angular2DataTableModule' imported by the module 'AppModule'`

Maybe **Angular2DataTableModule** don't include *.metadata.json for each of Angular files, @amcdnl ?

my question on stackoverflow: http://stackoverflow.com/questions/39867324/unexpected-value-x-imported-by-the-module-z-when-using-flag-aot/39868123#39868123

**Comment by amcdnl** [comment]
Its not AoT ready yet. PR's welcome if you wanna give it a run.

**Comment by istiti** [comment]
@amcdnl OK, Can you please follow these little step then this lib will be AoT compilable :) thanks in advance:
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.2lky7kgoe

**Comment by 2goatduo** [comment]
Here's a short-term fix until the npm distro is updated:

- linux bash syntax
$> git clone https://github.com/swimlane/angular2-data-table.git   &&  cd angular2-data-table
$> node_modules/.bin/ngc -p tsconfig.aot.json  # angular2-data-table already has tsconfig.aot-json

- ngc output .metadata.json files under dist/
- merge dist/ into release/ so .metadata.json files next to .d.ts files
$> rsync -abviuzP dist/ release/

- (optionally) back up directories
$> mv  $PROJECT-ROOT/node_modules/angular2-data-table/release  &nbsp; $PROJECT-ROOT/node_modules/angular2-data-table/npm-release
$> mv  $PROJECT-ROOT/node_modules/angular2-data-table/src  &nbsp;  $PROJECT-ROOT/node_modules/angular2-data-table/npm-src

- copy rebuilt 3rd party under node_modules
$>  cp -r release/   &nbsp; $PROJECT-ROOT/node_modules/angular2-data-table
$>  cp -r src/   &nbsp; $PROJECT-ROOT/node_modules/angular2-data-table

- aot build completed without any [static symbol errors](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.7ap5bf25g)
$> cd <project-root>  &&  ng build --prod --aot --output-path ng-aot

**Comment by istiti** [comment]
Are you sure the last version works? Can you please retry your solution with actual git version

**Comment by istiti** [comment]
@2goatduo I tried and get this error :

` Uncaught (in promise): ReferenceError: nameColumnHeader is not defined`

It's a ViewChild and I have it inside view <tempalte>

**Comment by 2goatduo** [comment]
@istiti Yes, I have noted some problems with this approach, but it worked for me on this commit: ef9156a176d160c3db7b41d43aa19fae93e4d85f .  One bug (which is relatively easy to fix) is that the rsync command above will copy not just .metadata.json files.  But I pulled the latest commit and now ngc fails altogether.  I'm looking at why.

**Comment by istiti** [comment]
It ok for me, just for AoT any  ViewChild decorator must have semicolons .... lol without --aot it compile fine without semis and with AoT you must put semis :)

**Comment by 2goatduo** [comment]
Update:  [ngc build of latest angular2-data-table fails.](https://github.com/swimlane/angular2-data-table/issues/224).  

Turns out that ngc and tsc can produce different output for all file types such as `.d.ts`, `.js`, `.js.map` and `.metadata.json`.  So, instead of rsync'ing files from (ngc produced) `/dist` into `/release`, it's simpler to copy the small set of files uniq to `/release` into `/dist` and then rename `/dist` to `/release`.

**Comment by istiti** [comment]
For me AoT works fine , Maybe better do something automatic and push it for community if you have time :) this will help a lot :) or Austin need do it each release to be sure it's released using aot

**Comment by amcdnl** [comment]
AoT is on my list very soon. Sorry just been busy w/ external things. If someone wants to add this I will gladly accept a PR.

**Comment by istiti** [comment]
I'm happy to close this issue too.
