### ISSUE TITLE
Test a component which use angular2-data-table

### ISSUE THREAD

**Issue by Caballerog** [swimlane/angular2-data-table#186]
**I'm submitting a ...**  (check one with "x")

```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I am developing testing  in a component that uses Angular2DataTable, but when the NgModuleTest are loading I find this error.

```
 TypeError: Cannot read property 'unsubscribe' of undefined
        at DataTable.ngOnDestroy (webpack:///src/components/DataTable.ts:117:24 <- src/test.ts:35681:28)

```

My code jasmine is the following:

```
import { Angular2DataTableModule } from 'angular2-data-table';
...

 beforeEach(() => {

    TestBed.configureTestingModule({
      declarations: [ProfileComponent],
      imports: [InlineEditorModule,
        Angular2DataTableModule,
        FormsModule,
        TranslateModule.forRoot()],
      providers: [
        {
          provide: Http, useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
            return new Http(backend, defaultOptions);
          }, deps: [MockBackend, BaseRequestOptions]
        },
        UserService,
        TranslateService,
        AppService,
        { provide: MockBackend, useClass: MockBackend },
        { provide: HttpToolsService, useValue: HttpToolsServiceStub },
        { provide: BaseRequestOptions, useClass: BaseRequestOptions }
      ]
    });

  });

```

I tried to mock DataTable component but I have not access to the DataTable component from the test environment. If I could access to DataTable component I would to do a mock like the following:

```

 fixture = TestBed.overrideComponent(DataTable, {
      set: {
        template: '<span>{{message}}</span>'
      }
    })
      .createComponent(DataTable);

```

**Expected behavior**

DataTable component to ngModuleTest envionment.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Testing angular apps.

**Please tell us about your environment:**

- **Table version:** 0.6.1
  
  
- **Angular version:** 2.0.1
  
  
- **Browser:** [all]
  
  
- **Language:** [all]

**Comment by amcdnl** [comment]
Interesting, can u create a demo? Or even better PR some tests for this project ;)

**Comment by Caballerog** [comment]
I can try it! But I still am a novice in angular2 testing apps (I've been testing a basic components in the last days).

**Comment by svanders** [comment]
I have a demo at https://github.com/svanders/angular2-data-table-bug-186

**Comment by amcdnl** [comment]
Any updates?
