### ISSUE TITLE
After resizing a column, any new click generates a new resize event 

### ISSUE THREAD

**Issue by lewisparma** [swimlane/angular2-data-table#196]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
After I resize a column, any click on the header generates a new resize of the previously resized column.
I managed to reproduce this with some custom styling.

**Expected behavior**
Column should be resized only when dragging the resize handle span.

**Reproduction of the problem**

https://plnkr.co/edit/vV1fVoHMJKSffcMISV5x?p=preview

To fix the issue is enough to make this small change to 'resizable.directive.ts' by adding **&& !this.subscription.closed** to the if block.

```
onMouseup() {
    this.resizing = false;

    if (this.subscription && !this.subscription.closed) {
      this.subscription.unsubscribe();
      this.onResize.emit(this.element.clientWidth);
    }
  }
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7, webpack dev server

* **Table version:** 0.7.x
0.93

* **Angular version:** 2.0.x
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by amcdnl** [comment]
Good find. Can you PR this please?

**Comment by lewisparma** [comment]
created pull request https://github.com/swimlane/angular2-data-table/pull/197
