### ISSUE TITLE
Sort trigger area is too small

### ISSUE THREAD

**Issue by colinfang** [swimlane/angular2-data-table#198]
Currently the sort click region is `.datatable-header-cell-label`. Is it possible to expand the click area so that a user can sort as long as he clicks on `.datatable-header-cell`?

I find my users often click on the space right after `.datatable-header-cell-label` on the header. And when he sees no responding from the table, he then automatically assumes there is no sort functional.

**Comment by amcdnl** [comment]
You can change the CSS style of the button. You could also pass a custom column header. Cheers!

**Comment by yaotzin68** [comment]
@colinfang how do you resolve it? I had the same issue

**Comment by dylandrollut** [comment]
@colinfang @amcdnl How would one go about increasing the click area size through CSS? By increasing the size of the margins and/or padding?
