### ISSUE TITLE
Table header elements order 

### ISSUE THREAD

**Issue by kaloczidev** [swimlane/angular2-data-table#20]
Ordering the columns by dragging the last element to the first place you loose the column and get a duplicated column.

**before:** 
![image](https://cloud.githubusercontent.com/assets/9059270/16947517/d23950fa-4daf-11e6-874c-fd9fbd825a2e.png)
**after:**
![image](https://cloud.githubusercontent.com/assets/9059270/16947530/e99c3f28-4daf-11e6-871a-f2c68f2a4bc0.png)

**Comment by amcdnl** [comment]
Ya, I've seen this...can't get it to happen everytime though, did you have any luck getting it to?

**Comment by kanipowa** [comment]
try relpalce the last and the first columns. it happens both directions (first->last, last->first).. for me its everytime causes the effect.

**Comment by amcdnl** [comment]
Is this still happening?
