### ISSUE TITLE
node_modules/angular2-data-table/ 404 (Not Found)

### ISSUE THREAD

**Issue by redplane** [swimlane/angular2-data-table#206]
hi everyone,

i'm new to angular 2, and now I'm using angular2-data-table for my SPA.
I've faced with a problem which said:

**http://localhost:3000/node_modules/angular2-data-table/ 404 (Not Found)**

In my systemjs.config.js, if I set : 
**'angular2-data-table':         'https://unpkg.com/angular2-data-table'**
My app works 

But if I set:
**'angular2-data-table':         "../node_modules/angular2-data-table"**
The error happens.

Can anyone help me please ?
Thank you,

**Comment by criticalpixel** [comment]
Have you installed the package?
You need to install angular2-data-table package if you wish to use it from local directory.

install via npm
```
npm install angular2-data-table --save
```

**Comment by redplane** [comment]
I've found the solution for my problem:
Here is my **systemjs.config.js** :
```
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            'angular2-data-table':         "npm:angular2-data-table"
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'angular-in-memory-web-api': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'angular2-data-table': {
                main: './release/index.umd.js',
                defaultExtension: 'js'
            }
        }
    });
})(this);

```

This configuration must be included in **packages** :
```
'angular2-data-table': {
                main: './release/index.umd.js',
                defaultExtension: 'js'
            }
```

Hope this helps anyone faces the problem as I did.
