### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by luyang177** [swimlane/angular2-data-table#21]
- Type 'npm install angular2-data-table' in cmd without error
- enter '\node_modules\angular2-data-table'
- type 'npm start', them errors below:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.1.14 start: `npm-run-all -s clean:* start:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-data-table@0.1.14 start script 'npm-run-all -s clean:* start:server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -s clean:* start:server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     F:\web-project\node_modules\angular2-data-table\npm-debug.log

**Comment by amcdnl** [comment]
you need to do `npm run install:global` first

**Comment by luyang177** [comment]
This time I run 'git clone https://github.com/swimlane/angular2-data-table.git'
And type 'npm run install:global', then it seems no errors.
I type 'npm start', then errors below:


F:\web-project\angular2-data-table>npm start

> angular2-data-table@0.1.14 start F:\web-project\angular2-data-table
> npm-run-all -s clean:* start:server


> angular2-data-table@0.1.14 clean:dist F:\web-project\angular2-data-table
> ./node_modules/rimraf/bin.js dist

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "clean:dist"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.1.14 clean:dist: `./node_modules/rimraf/bin.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-data-table@0.1.14 clean:dist script './node_modules/rimraf/bin.js dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/rimraf/bin.js dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     F:\web-project\angular2-data-table\npm-debug.log
ERROR: "clean:dist" exited with 1.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.1.14 start: `npm-run-all -s clean:* start:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-data-table@0.1.14 start script 'npm-run-all -s clean:* start:server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -s clean:* start:server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     F:\web-project\angular2-data-table\npm-debug.log

**Comment by luyang177** [comment]
Since I can not run ./node_modules/rimraf/bin.js directly in windows, I miss something to run js?
I know little js.
