### ISSUE TITLE
onRowClick is never triggered

### ISSUE THREAD

**Issue by crebuh** [swimlane/angular2-data-table#215]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Added (onRowClick)="_onRowClick($event)" as attribute to the datatable-elmement in the template. But _onRowClick-Method is never executed = event emitter is not working.

**Expected behavior**
_onRowClick should be executed each time a row has been click. 

**Reproduction of the problem**
add the following line to the template:

      <datatable class='table table-hover material' [rows]='list' [options]='options' (onRowClick)="_onRowClick($event)"></datatable>

and the callback in the component

          private _onRowClick(row) {
        console.log(row);
    }

**Please tell us about your environment:**
Ubuntu 16.04, Visual Studio Code, NPM 4.6, npm 3.10.9, webpack

* **Angular version:** 2.1.0

* **Browser:**  all

* **Language:** all

**Comment by amcdnl** [comment]
Can you see if this is getting triggered? https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/body.component.ts#L253

Also a demo would be helpful. :)

**Comment by crebuh** [comment]
@amcdnl I updated to the latest version and now it is work. can be closed. thank you!

**Comment by jonnparkertx** [comment]
I'm experiencing the same problem. Using 1.7.0 (also tried 1.5.0)

**Comment by amcdnl** [comment]
The api changed in 1.0, see docs: https://swimlane.gitbooks.io/angular2-data-table/content/api/table-outputs.html#activate
