### ISSUE TITLE
No instructions on how to add icons

### ISSUE THREAD

**Issue by niklas-dahl** [swimlane/angular2-data-table#217]
**I'm submitting a ...**  (check one with "x")

```
[x] missing documentation
```

**Current behavior**

When not including `<link href="https://file.myfontastic.com/Jnf54BZCm7mSjGCxNRbfp3/icons.css" rel="stylesheet">` the icons for sorting are missing.

But this is no where mentioned AFAIK.

**Expected behavior**

It should probably be noted here: https://swimlane.gitbooks.io/angular2-data-table/content/introduction/installing.html

Maby even bundle the icons with the table.

**What is the motivation / use case for changing the behavior?**

I spend time figuring out why my icons were missing,

**Comment by amcdnl** [comment]
Good call. I think in most cases people use their own set from material/fontawesome/bootstrap/etc. I'll add some docs tho

**Comment by maxisam** [comment]
For people who want to use font-awesome with datatable 

here is the setup I used.

<script src="https://gist.github.com/maxisam/7130954b383647e32bab38e4259c9e17.js"></script>

**Comment by amcdnl** [comment]
You can manually pass the icon names now so this shouldn't be needed.

**Comment by maxisam** [comment]
Ah ha ! I see. Thx

**Comment by SOftEngrAtta** [comment]
#amcdnl  where is the table html generate in module , basically i didnot found previous and next button in ngx datatable

**Comment by spo** [comment]
@amcdnl Can you give me a hint how to pass the icons manually... Thanks
