### ISSUE TITLE
Table header with rowspan

### ISSUE THREAD

**Issue by johnnyWMobile** [swimlane/angular2-data-table#219]
Hi, I would like to create a datatable with 2 level table header (i.e. rowspan=2). Would that library caters for this? Thanks.

**Comment by amcdnl** [comment]
Please use the form for Github Issues in the future.

Can you explain your use case? Perhaps this could be accomplished currently w/ some trickery.

**Comment by asko1205** [comment]
I have the same issue. Trying to create a header that looks something like this:

![snip20161024_1](https://cloud.githubusercontent.com/assets/9523459/19652513/df4c468c-99c5-11e6-91b0-6e5aeaade1d3.png)

This is possible in regular datatables (https://datatables.net/examples/advanced_init/complex_header.html), but I would love to know if this could be accomplished with angular2-data-table (even w/ some trickery). Thanks!

**Comment by amcdnl** [comment]
Ya, you could do this with header templates. Just make empties where you want the row span w/ css.
