### ISSUE TITLE
demo app run fails on npm install

### ISSUE THREAD

**Issue by ihabZhaika** [swimlane/angular2-data-table#220]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

The starter code npm install fails when following this

https://swimlane.gitbooks.io/angular2-data-table/content/introduction/installing.html

 On this step :

npm i

`npm ERR! Linux 4.8.0-26-generic
npm ERR! argv "/home/ihab/progs/node-v4.6.0/bin/node" "/home/ihab/progs/node-v4.6.0/bin/npm" "i"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/compiler@2.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.1.1 wants @angular/compiler@2.1.1
npm ERR! peerinvalid Peer @angular/platform-server@2.1.1 wants @angular/compiler@2.1.1
npm ERR! peerinvalid Peer @angular/compiler-cli@0.6.4 wants @angular/compiler@2.0.2
`
**Expected behavior**

install should pass

**Reproduction of the problem**

pull the repo , then npm i

**Comment by amcdnl** [comment]
You need Node 6+ to run demos.
