### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by retallicka** [swimlane/angular2-data-table#221]
I was looking at documentation here:

https://swimlane.gitbooks.io/angular2-data-table

Another user in another issue (#205) mentioned a header template and I did not know this was possible. I had to look at the demos in 0.9.3 to see it. Then I realised there's been a few releases now since 0.9.3

Also great work on this project :)

**Comment by amcdnl** [comment]
`headerTemplate` property is listed here -> https://github.com/swimlane/angular2-data-table/blob/master/docs/api/column_options.md

**Comment by retallicka** [comment]
Ok but I think you should update the template demo too :) template-dom.ts and template-obj.ts I found helpful and I couldn't find them in the docs, only https://swimlane.gitbooks.io/angular2-data-table/content/examples/templates.html which wasn't as helpful
