### ISSUE TITLE
Remove an element from a sorted table

### ISSUE THREAD

**Issue by Helayxa** [swimlane/angular2-data-table#222]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When trying to remove a row from the sorted table, the row is removed but the table isn't sorted any more

**Expected behavior**

When removing a row from the the sorted table, the table should keep its sort options.

**Reproduction of the problem**

http://plnkr.co/edit/Et15LdvnddzyJafqLlM6
If you remove the first element, no problem. Now sort by name, and remove an element. The table isn't sorted anymore... Maybe because "rows" isn't updated with the sort ?

**What is the motivation / use case for changing the behavior?**

I would like to keep sorted data when I remove an element, instead of changing my sorting everytime I remove an element.

Thanks a lot for your time and your great job !

**Comment by amcdnl** [comment]
Fixed in 2.1.3
