### ISSUE TITLE
Date sorting

### ISSUE THREAD

**Issue by nirhu** [swimlane/angular2-data-table#229]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When sorting columns that have Date data, rows are sorted according to stringified version of them. (Thursday is before Sunday, no matter the actual date).

**Expected behavior**
Sorting according to actual date.

**Reproduction of the problem**
Just use Date object as property of column.

**What is the motivation / use case for changing the behavior?**
Proper sorting.

* **Table version:** 0.11.2

* **Angular version:** 2.1.1

* **Browser:** [ Chrome 54.0.2840.71 m ]

**Comment by amcdnl** [comment]
A custom sort function can be passed to accomplish this. See: https://github.com/swimlane/angular2-data-table/blob/master/src/demos/sorting-server.ts#L42
