### ISSUE TITLE
Error while running install:global

### ISSUE THREAD

**Issue by ranjinisethuram** [swimlane/angular2-data-table#23]
I was able to successfully install angular2-data-table using npm but ran into problem while executing **npm run install:global** command. Below is the error report. 

I would also like to mention that I tried running this command since importing angular2-data-table was throwing error saying this module is not found.Any help would be immensely useful.
Thanks in advance. 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "npm-run-all" "rollup" "module-hea
der" "postcss" "npm-check" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path C:\Users\Admin\AppData\Roaming\npm\node_modules\module-header
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Admin\AppData\R
oaming\npm\node_modules\module-header' -> 'C:\Users\Admin\AppData\Roaming\npm\no
de_modules\.module-header.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\a
ction\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Admin\AppData\R
oaming\npm\node_modules\module-header' -> 'C:\Users\Admin\AppData\Roaming\npm\no
de_modules\.module-header.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\Admin\AppData\
Roaming\npm\node_modules\module-header' -> 'C:\Users\Admin\AppData\Roaming\npm\n
ode_modules\.module-header.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\a
ction\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Admin\AppData\R
oaming\npm\node_modules\module-header' -> 'C:\Users\Admin\AppData\Roaming\npm\no
de_modules\.module-header.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apache-tomcat-7.0.59\webapps\angular-workspace\src\main\webapp\c
lient\node_modules\angular2-data-table\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "install:global"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-data-table@0.1.14 install:global: `npm install npm-run-all rol
lup module-header postcss npm-check -g`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the angular2-data-table@0.1.14 install:global script 'npm ins
tall npm-run-all rollup module-header postcss npm-check -g'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-data-table p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install npm-run-all rollup module-header postcss npm-check -g
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-data-table
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-data-table
npm ERR! There is likely additional logging output above.

**Comment by amcdnl** [comment]
Just ran this w/o problems, can you try again? http://www.screencast.com/t/eblt4sWW

**Comment by ranjinisethuram** [comment]
No luck yet ! I get same error. I see from the error report that there is some problem in installing module-header.But do not know why.

**Comment by amcdnl** [comment]
Odd, does it work in a new project?

**Comment by luyang177** [comment]
Please try running this command again as root/Administrator.

The error report said clear.
