### ISSUE TITLE
deep getter does not handle 'null/undefined' properties

### ISSUE THREAD

**Issue by lewisparma** [swimlane/angular2-data-table#232]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I have a dynamic set of objects as data source for the table. Some have a property called 'system' and others don't. If I bind a column to 'system.name' the deepValueGetter method will crash.

**Expected behavior**
deepValueGetter should expect that some properties in the middle of the path can be null/undefined..

**Reproduction of the problem**

a simple check if the property is null/undefined in deepValueGetter should fix the issue.

current = current[split[i]];
 if (!current) {
     return '';
 }

**What is the motivation / use case for changing the behavior?**
Support a data source of objects that have a dynamic set of properties.

**Please tell us about your environment:**

* **Table version:** 0.7.x
0.11.2

* **Angular version:** 2.0.x
2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by amcdnl** [comment]
Fixed!

**Comment by lewisparma** [comment]
Thnks
