### ISSUE TITLE
can you please coulmn "visible" and "searchable" ?

### ISSUE THREAD

**Issue by eliadAyehu** [swimlane/angular2-data-table#236]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
we cant define column as visible or searable to filter.

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Thanks for your suggestion, however, I believe this is out of scope for this project. Both of these can be accomplished w/ the existing APIs. Please read: https://swimlane.gitbooks.io/angular2-data-table/content/introduction/architecture.html for more info.
