### ISSUE TITLE
Scroller.ngOnDestroy: removeEventListener requires 2 arguments

### ISSUE THREAD

**Issue by pamtbaau** [swimlane/angular2-data-table#237]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
**Error message:**
TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

**Location of error**: scroller.directive.ts
```
ngOnDestroy() {
    if(this.scrollbarV || this.scrollbarH) {
      this.parentElement.removeEventListener('scroll');
    }
  }
```

**Comment by amcdnl** [comment]
Is there any side effects of this?

**Comment by pamtbaau** [comment]
Yes, my Electron app crashes...

**Comment by amcdnl** [comment]
Thanks for letting me know. I will resolve this today.

**Comment by amcdnl** [comment]
Should be fixed in master
