### ISSUE TITLE
Change "Total" in other language in DataTable footer

### ISSUE THREAD

**Issue by derchirurg** [swimlane/angular2-data-table#240]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

I want to change the "Total" at the footer of the DataTable. Is this possible per config or something?

**Please tell us about your environment:**

* **Table version:** 0.12.0

* **Angular version:** 2.2.1

* **Browser:** [all ]

* **Language:** [all]

**Comment by amcdnl** [comment]
Done in 1.0!
