### ISSUE TITLE
Removing rows with scrollbarV set to true doesn't remove all the rows

### ISSUE THREAD

**Issue by ocombe** [swimlane/angular2-data-table#242]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
When scrollbarV is set to true, updating rows doesn't remove the last one (if new index < last index). It splices the rows with nb of rows + 1 (instead of nb of rows) which means that if you have 10 rows and remove 9, then 2 rows will be left instead of 1.
I've narrowed the bug to this line of code: https://github.com/swimlane/angular2-data-table/blob/master/src/services/state.service.ts#L91
Notice the `+ 1` at the end. I think that there is this + 1 because when you have a scrollbar, you want the last line to be visible even if the line is cropped. For example if you have 50 rows and only 10 are visible, but their total height takes 98% of the table height, you still want to show the 11th row so that you can see that there are more rows invisible (yet) below.
I see two ways to fix this: check if the current visible number of rows is less than the total of rows, in which case add `+ 1`, and if it's equal to the total number then remove the `+ 1`. Another way would be to add `true` to `this.updateRows()` here: https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/body.component.ts#L137 and this way the splice index would always be the correct number of rows here: https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/body.component.ts#L179
I'm not even sure why there is a `refresh` option in this method, it should always use the real total number of rows for the splice but maybe there's a case I don't see here.

**Expected behavior**
It should remove all rows that have been deleted from the model.

**Reproduction of the problem**
http://plnkr.co/edit/bGk5ZbAwcjYhPb2gDNfo?p=preview
There's another bug here where the init row don't appear (already reported in #241), use the scrollbar to make them appear. Then press the button "replace all with 1 new row", and you will see 2 rows left instead of just one.

* **Table version:** 0.12.0

* **Angular version:** 2.1.2

* **Browser:** all

* **Language:** all

**Comment by RonnyLV** [comment]
+1

Same problems here.

**Comment by amcdnl** [comment]
Can you retry on 1.0.0?

**Comment by ocombe** [comment]
It's fixed in 1.0.0, thanks !
