### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by RonnyLV** [swimlane/angular2-data-table#246]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

Resizing using resize handles doesn't work.

**Reproduction of the problem**
Using Demo page on every demo, try to resize columns using handles.

* **Table version:** 1.0.0

* **Browser:** [ Chrome Version 54.0.2840.71 m (64-bit) ]

**Comment by amcdnl** [comment]
I did this just last night. What browser and OS?

**Comment by RonnyLV** [comment]
Chrome 54.0.2840.71 m (64-bit) Windows 7

**Comment by amcdnl** [comment]
I was on Mac, maybe that's it

**Comment by amcdnl** [comment]
Can u re-verify on 1.2?

**Comment by Atsman** [comment]
@amcdnl i am using windows 10 and chrome Version 56.0.2905.1

**Comment by amcdnl** [comment]
Did you try on 1.2?

**Comment by Atsman** [comment]
@amcdnl no i didn't, i see it on github pages

**Comment by Atsman** [comment]
@amcdnl i think that i got it. Should it be possible to resize column in force mod? As i can understand from the docs, it shouldn't. So it shouldn't be possible to start resize in header. 

i cloned repo and see that in version 1.2

**Comment by davidmjames** [comment]
I see the same issues on 1.2- Chrome on Mac (64bit):  54.0.2840.71

**Comment by RonnyLV** [comment]
Still the same with 1.3

**Comment by colinfang** [comment]
@Atsman  I used to be able to resize in force mode in v0.9

**Comment by amcdnl** [comment]
Ya, you should be able to still resize in forced. So perhaps thats your issue?

**Comment by amcdnl** [comment]
fixed in 1.3.1
