### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'datatable'

### ISSUE THREAD

**Issue by Andranik-89** [swimlane/angular2-data-table#247]
bug perhaps.

Good day everyone. In all the plnkr examples there is a bug that says - Can't bind to 'options' since it isn't a known property of 'datatable'

It apeared just today, yesterday it was fine.
here are examles:
https://embed.plnkr.co/1smAAsVusofOjq6h7Avh?show=preview&autoCloseSidebar=true
https://embed.plnkr.co/I4Z2FibupHPGYVUXQGYh/

**Comment by shattar** [comment]
The options input was removed and the options were exploded into individual inputs.  See the demo examples.

**Comment by amcdnl** [comment]
This is true. This was a major version with breaking api changes. You can checkout the changelog for more info
This was done in an effort to make the component more reactive and declarative.
