### ISSUE TITLE
Table data update

### ISSUE THREAD

**Issue by nirhu** [swimlane/angular2-data-table#248]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
When updating data, the cells update only when clicking on them (blur), not when the data changes. This worked well in 0.11.2.

**Expected behavior**
Table updates, when data updates.

**Reproduction of the problem**
Just change some data in the background (e.g. button click) and then click the cell that was supposed to reflect the change. The cell updates only on click.

**What is the motivation / use case for changing the behavior?**
To see the updated data.

* **Table version:** 1.0.0

* **Angular version:** 2.1.1

* **Browser:** [Chrome 54 ]

**Comment by amcdnl** [comment]
This is a side effect of the OnPush change detection strategy. See: https://swimlane.gitbooks.io/angular2-data-table/content/introduction/architecture.html#onpush for more info.

**Comment by nirhu** [comment]
Oh, ok thanks.

**Comment by nirhu** [comment]
So how do I update the table now? I read the article, but it is still not clear to me.

**Comment by colinfang** [comment]
@nirhu  you can do `row = row.slice()` to force change the reference of `row` if it is modified in place.
