### ISSUE TITLE
Resizing container does not trigger body columns to resize, only header columns.

### ISSUE THREAD

**Issue by shattar** [swimlane/angular2-data-table#251]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When resizing the container (window), the header column widths resize, but the body column widths do not (until the underlying row data changes or an event is triggered that effects that row like clicking it).

**Expected behavior**
On window/container resize, I expect that widths of the column header and every row of the body to resize at the same time.

**Reproduction of the problem**
Resize the window of many of the non-fixed column width demos.
[Auto Height Demo](http://swimlane.github.io/angular2-data-table)

**Please tell us about your environment:**

* **Table version:** 1.1.0

* **Angular version:** 2.1.2

* **Browser:** Google Chrome: 54.0.2840.71 (Official Build) m (32-bit)

* **OS:** Windows

**Comment by amcdnl** [comment]
Fixed in 1.2.0
