### ISSUE TITLE
Resizing a column ignores cell template.

### ISSUE THREAD

**Issue by shattar** [swimlane/angular2-data-table#252]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When resizing an individual column by dragging the header column dividers, where the body cells use a template, the template is ignored and the value is directly shown.

**Expected behavior**
The cell template is used to render the cell contents, even when the column is resized.

**Reproduction of the problem**
Resize the 'Gender' or 'Age' columns in the [Templates Inline Demo](http://swimlane.github.io/angular2-data-table)

**Please tell us about your environment:**

* **Table version:** 1.1.0

* **Angular version:** 2.1.2

* **Browser:** Google Chrome: 54.0.2840.71 (Official Build) m (32-bit)

* **OS:** Windows

**Comment by amcdnl** [comment]
Fixed in 1.2
