### ISSUE TITLE
Multiselection is not working after release  1.2.0

### ISSUE THREAD

**Issue by RuslanKurtjanyk** [swimlane/angular2-data-table#256]

**Comment by amcdnl** [comment]
Is it not working at all? Is only some scenarios not working? 

Please do not log bugs like this, there is a template for a reason.

**Comment by vbolshutkin** [comment]
I just encountered this project while looking for table with multiselect feature, and noticed that the feature doesn't work right now with no messages in console http://swimlane.github.io/angular2-data-table/#

**Comment by amcdnl** [comment]
Seems to work for me, demo was messed up though.
