### ISSUE TITLE
facing issue to incorporate angular2-data-table

### ISSUE THREAD

**Issue by nehak2** [swimlane/angular2-data-table#258]
Steps followed :
1) npm install angular2-data-table
2) included following code in system.config.js
map: {
'angular2-data-table':  'node_modules/angular2-data-table/release',
}
packages: {
'angular2-data-table':  { 
		main: './index.js',
        defaultExtension: 'js' 
      }
 }
3) added entry in @ngModule as follows
import {Angular2DataTableModule} from 'angular2-data-table/release/datatable.module';
imports: [Angular2DataTableModule
],
4) made server paginng component and tried using angular2-data-table in template
template: `
    <div>
      <h3>Server-side Paging</h3>
      <datatable
        class="material"
        [rows]="rows"
        [columns]="[{name:'Name'},{name:'Gender'},{name:'Company'}]"
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        [rowHeight]="'auto'"
        [externalPaging]="true"
        [count]="count"
        [offset]="offset"
        [limit]="limit"
        (page)='onPage($event)'>
      </datatable>
    </div>
  `
  but facing following errors: 
  Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:34 Error: Error: XHR error (404 Not Found) loading http://localhost:8080/node_modules/angular2-data-table/release/release/datatable.module.js(…)(anonymous function) @ localhost/:34

Please help , looking forward to use server side paging.
It would be great if anyone can share proper steps.

**Comment by amcdnl** [comment]
You don't need to do this: `import {Angular2DataTableModule} from 'angular2-data-table/release/datatable.module';`....its just `import {Angular2DataTableModule} from 'angular2-data-table`;
