### ISSUE TITLE
Column name is case sensitive

### ISSUE THREAD

**Issue by Kianian** [swimlane/angular2-data-table#259]
I tried to bind data into data-table and spent 2 hours to fix it, I found this:

If I use the column name in upper-case it doesn't show anything.

this.cols = [{"name":"id"},{"name":"FirstName"}];
this.data = [{"id":100,"FirstName":'xyz'}];

It works only if I change the column names into lower case.

**Comment by amcdnl** [comment]
Use `prop` if you need specific attributes. If props are not supplied, it camel cases the name thus your issue.
