### ISSUE TITLE
Add Support On Multiple Select With CTRL(control)

### ISSUE THREAD

**Issue by germanAd** [swimlane/angular2-data-table#260]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Expected behavior**
Multiple select with CTRL

* **Angular version:** 2.0.x

* **Language:** TypeScript

**Comment by amcdnl** [comment]
This should already happen automatically on `selectionType=multi`

**Comment by istiti** [comment]
Yes but by click not durning Ctrl + click

**Comment by germanAd** [comment]
I added my code to existing for supporting in Ctrl+click

**Comment by istiti** [comment]
@germanAd can you PR please it's interesting 👍

**Comment by amcdnl** [comment]
Ya, would love to have that in master.

**Comment by germanAd** [comment]
@istiti 
I not have time add this to master
I can write here changed i made
Its ok?
