### ISSUE TITLE
only one column 'force' resize bug

### ISSUE THREAD

**Issue by istiti** [swimlane/angular2-data-table#263]
Hi,

I have only one "column" and I set columnMode to 'force' but I still have in 1.3.1 problem when resize my window, you can check here my simple code and my screenshot : 
## Code 
           <datatable
                    style="height:calc(100vh - 113px)"
                    class='material'
                    [ngClass]="{'visibile-hidden': load || dataFiles.length === 0}"
                    [rowHeight]="70"
                    [headerHeight]="50"
                    [columnMode]="'force'"
                    [scrollbarV]="true"
                    [selectionType]="'single'"
                    [rows]='dataFiles'
                    [columns]="columns"
                    (select)="onRowClick($event)">
            </datatable>
            <template #nameColumnHeader let-column="column"> .... </template>
            <template #nameColumnBody  let-row="row" let-value="value" > ... </template>

## Gif 
![strange_when_resize](https://cloud.githubusercontent.com/assets/2789203/20091378/c1db0358-a592-11e6-8026-114c5c7e241e.gif)

**Comment by amcdnl** [comment]
Can you make a plunkr showing this?

**Comment by istiti** [comment]
@amcdnl  nop because it's fixed in 1.4.0  💃 👍  🎉 I will close this issue but will open another because when I scroll my datatable then change the TAB... scroll keep same position, it is not on TOP when changing tab
