### ISSUE TITLE
Cannot find name 'IntersectionObserver

### ISSUE THREAD

**Issue by penndai** [swimlane/angular2-data-table#268]
"Cannot find name 'IntersectionObserver'" when I try to use Row Detail in angular2-data-table module.
I create project files by angular-cli, and use webpack.

![pastedimage](https://cloud.githubusercontent.com/assets/9718210/20121863/ee581918-a667-11e6-864e-85a34a61d9e2.png)

**Comment by amcdnl** [comment]
Fixed in 1.4.0

**Comment by penndai** [comment]
Hi, I installed it yesterday, so I think it should be the latest version. Or how can I check the version number from ngmodule?

**Comment by penndai** [comment]
Hi,

  From the github, the latest version is 1.3.1, no 1.4.

[cid:e85e5fc9-e28a-45f3-94c5-a09f3e164c8b]


________________________________

**Comment by penndai** [comment]
![capture](https://cloud.githubusercontent.com/assets/9718210/20125212/30a8f0fe-a680-11e6-8616-4f661e1bca27.PNG)

**Comment by amcdnl** [comment]
Just released ;)

**Comment by penndai** [comment]
Thanks. That is so great!


________________________________
