### ISSUE TITLE
loadingIndicator Behaviour Not As Expected from 0.6.1 to 1.4.0

### ISSUE THREAD

**Issue by mashaalmemon** [swimlane/angular2-data-table#271]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Must I now turn the loadingIndicator on/off explicitly myself through code? After the refactor?
```

**Current behavior**
I upgraded from v0.6.1 to the latest 1.4.0. I noticed many breaking changes which are fine. I am looking for clarification on the "loadingIndicator". Must I set the loadingIndicator to 'true'/'false' explicitly each time populate the table?

**Expected behavior**
The loading indicator used to turn on/off itself. It does not do this any more. 

**Reproduction of the problem**
 Set loadingIndicator to "true"

**What is the motivation / use case for changing the behavior?**
Turn on loading indicator automatically when loading data.

**Please tell us about your environment:**

OSX Sierra (dev env)
Hapi

* **Table version:** 0.7.x
1.4.0
* **Angular version:** 2.0.x
2.1.1

* **Browser:** [all]

* **Language:** [TypeScript 2.X | ES6]

**Comment by istiti** [comment]
Second it! 
I reported same behavior on gitter thanks to take time to weite issue !

**Comment by amcdnl** [comment]
Yes, I made it a explicit call now. 

I can switch it but I think its up to the dev to determine when to show it. Naively doing it before was a bit odd after review. Open to thoughts on how to handle this.

**Comment by tahaerden** [comment]
@amcdnl  Do you think it is a good idea to use the following options?:

[rows]="rows"
[loadingIndicator]="!rows"

Assuming rows variable doesn't have an initial value, and assigned to an Array object when the data is pulled.

It seems to be working nice for me but I wanted to ask just in case as I'm new with this package.
