### ISSUE TITLE
Release/index.js generates an error Unexpected token '<'

### ISSUE THREAD

**Issue by pverdu** [swimlane/angular2-data-table#272]
Why is the index.js in release folder not correctly compiled by webpack?
The 0.12.0 version contains `(function webpackUniversalModuleDefinition(root, factory) {` at the start of the file. All later versions contain only the javascript version of the src/index.ts file.

Problem im facing here is that the data.module file is containing the main html code, since the data module file can't be find.
The "Unexpected token '<'" problem.

```
Evaluating http://cha.dev/node_modules/angular2-data-table/release/datatable.module <-- goes wrong here
Evaluating http://cha.dev/node_modules/angular2-data-table/release/index.js
Evaluating http://cha.dev/bundles/ChaBundle/Resources/ts/payment/payment.module.js
```

I tried building the project myself running npm install and npm run release, but there are alot of errors. 

Could you guide as in the right direction? We don't have a lot of experience yet with Angular2, Webpack or UMD.

0.12.0 is working fine, but we need the server paging feature, so we really want to make use of the latest 1.4.0 version.

**Comment by amcdnl** [comment]
I don't think I'll be able to help with that information provided.

I have not seen others having such issues, perhaps its related to your node environment? If you could make a demo, I'll reopen and dig in.

**Comment by pverdu** [comment]
I don't get it. Systemjs can find the './datatable.module' file and evaluates it, but then it can't find and therefor evaluate the index.js file in './component'. 
Am i forgetting something in my systemjs.config.js? My systemjs.config.js file looks like this:

```
/**
 * System configuration for Angular modules
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'bundles/ChaBundle/Resources/ts',
      payment: 'bundles/ChaBundle/Resources/ts/payment',
      shared: 'bundles/ChaBundle/Resources/ts/shared',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
      'angular2-data-table': 'npm:angular2-data-table/release'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      },
      'angular2-data-table': {
        main: 'index.js',
        defaultExtension: 'js'
      }
    }
  });
})(this);
```
