### ISSUE TITLE
ngFor Not working in the datatable-row-detail-template

### ISSUE THREAD

**Issue by penndai** [swimlane/angular2-data-table#274]
Hi, 
  I have the class Step which contains another list of object, let's say Items, when I try to use row-detail to display them. I can display steps as following screenshot, but no detail medication displayed.

  ```
 <datatable-row-detail-template>
          <template let-row="row">
            <div style="padding-left:35px;">
              <div><strong>Medication</strong></div>
              <div>{{row._medication[1]._name}}, {{row._medication[0]._name}}</div>
              <div>
                <ul>
                  <li *ngFor="let item of row._medication">
                    {{item._name}}
                  </li>
                </ul>
              </div>
           </div>
          </template>
        </datatable-row-detail-template>
```
  Can anyone try ngFor in detail template before?
 
![capture](https://cloud.githubusercontent.com/assets/9718210/20174951/9a65b350-a794-11e6-8464-7b0cfcf31a48.PNG)

![capture](https://cloud.githubusercontent.com/assets/9718210/20175035/ff9b9532-a794-11e6-8b59-3b787f4d3225.PNG)

When I comment out ngFor, I can display the first or second item in the array as below:

```
 <datatable-row-detail-template>
          <template let-row="row">
            <div style="padding-left:35px;">
              <div><strong>Medication</strong></div>
              <div>{{row._medication[1]._name}}, {{row._medication[0]._name}}</div>
            </div>
          </template>
 </datatable-row-detail-template>
```
![capture](https://cloud.githubusercontent.com/assets/9718210/20175139/6a15a560-a795-11e6-8534-6b47d6335da9.PNG)

**Comment by scotteby** [comment]
I was able to reproduce this exact issue as well today. ngFor would be very helpful to display a sub list.

**Comment by amcdnl** [comment]
Interesting, I'm not sure why this wouldn't work.

**Comment by penndai** [comment]
Austin, can I ask whether detail template support sub table /nested table? ngFor is just a easier substitution for my original idea, I tried to use sub table before. But find even simple ngFor didn't work.

**Comment by amcdnl** [comment]
Fixed in 2.0

**Comment by penndai** [comment]
Thanks, I will try it soon!

**Comment by penndai** [comment]
Now when I update the ng2-datatable version to 2.0.0, or even latest 2.1.3, I got the error, it seems can't load the datatable properly.  Please see attached file:
1. package.json

![capture1](https://cloud.githubusercontent.com/assets/9718210/20923094/f6e59f4a-bbfe-11e6-97b5-1ebe8877d58d.PNG)
2. error on the page console:
![capture2](https://cloud.githubusercontent.com/assets/9718210/20923109/0894542a-bbff-11e6-8fab-7d75caa98725.PNG)
3. when I try to update the dependencies, some warning messages:
![capture3](https://cloud.githubusercontent.com/assets/9718210/20923118/1c8a3558-bbff-11e6-9a9d-e03154547a92.PNG)

**Comment by amcdnl** [comment]
Please make a demo reproducing this, I can't do much with the above info.
