### ISSUE TITLE
Datatable columns not showing inline

### ISSUE THREAD

**Issue by TheBurgerShot** [swimlane/angular2-data-table#277]
Hey guys,

I might be doing something wrong since I don't see any other posts regarding this problem, but I assume I am not since I'm experiencing this issue with a just created project as well.

I am just trying to create a data-table, but the columns are showing up underneath each other instead of next to each other.

I have simply copied the basic example that can be found in the 'demo' folder

```
@Component({
  selector: 'app-root',
  template: `
  	<div>
      <h3>Fluid Row Heights</h3>
      <datatable
        class="material"
        [rows]="rows"
        [columns]="columns"
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        [rowHeight]="'auto'">
      </datatable>
    </div>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  rows = [];

  columns = [
    { prop: 'name' },
    { name: 'Gender' },
    { name: 'Company' }
  ];

  constructor() {
    this.fetch((data) => {
      this.rows = data;
    });
  }

  fetch(cb) {
    const req = new XMLHttpRequest();
    req.open('GET', `assets/data.json`);

    req.onload = () => {
      cb(JSON.parse(req.response));
    };

    req.send();
  }
}
```

but even with just a clean newly created project, with only this plugin added, the problem still occurs:

![image](https://cloud.githubusercontent.com/assets/5908466/20246048/da40c638-a9ae-11e6-9cc7-d022f3b4c221.png)

Any ideas?

**Comment by shattar** [comment]
Did you import the datatable css styles?

**Comment by TheBurgerShot** [comment]
@shattar Thanks, that was it. Not very clear that's required imo though. Thanks a lot!

**Comment by ManhLQ** [comment]
I tried to import style from datatable but nothing change.
Did I miss something?

```sass
@import '~angular2-data-table/release/datatable.css';
@import '~angular2-data-table/release/material.css';
```

```typescript
...
import { NG_TABLE_DIRECTIVES } from 'ng2-table';
...

@Component({
    selector: 'my-component',
    template: `
        <swui-datatable class="material" [rows]="rows" [columns]="columns">
        </swui-datatable>
    `,
    styleUrls: ['./myStyle.scss'],
    providers: [MyService]
})
export class MyComponent {

    rows = [
        { name: 'Austin', gender: 'Male', company: 'Swimlane' },
        { name: 'Dany', gender: 'Male', company: 'KFC' },
        { name: 'Molly', gender: 'Female', company: 'Burger King' },
    ];
    columns = [
        { prop: 'name' },
        { name: 'Gender' },
        { name: 'Company' }
    ];

    constructor() { }

}

```

**Comment by parialegend** [comment]
@ManhLQ Did you get it working.
I am having the same issue.
@TheBurgerShot  You added the scss files or the css files. Both did not work in my case.

**Comment by amcdnl** [comment]
I'm gonna be adding this by default in next release.
