### ISSUE TITLE
Implements ngOnChange() for paging limit

### ISSUE THREAD

**Issue by JeanPascalR** [swimlane/angular2-data-table#282]
Hi,

First of all, thank you for developing angular2-data-table, a very useful component.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The page size cannot be changed dynamically. In **datatable.component.ts**:
`// Page size
  @Input() limit: number = undefined;`

**Expected behavior**
It would be a great feature to handle dynamic change of this property

**Suggestion**
It is apparently possible to do so thanks to:
`ngOnChanges(changes: SimpleChanges)`

> Lifecycle hook that is called when any data-bound property of a directive changes.

[Angular docs](https://angular.io/docs/ts/latest/api/core/index/OnChanges-class.html)

Thanks

JPR

**Comment by amcdnl** [comment]
The table implements `OnPush` change detection. See: https://swimlane.gitbooks.io/angular2-data-table/content/introduction/architecture.html for more info
