### ISSUE TITLE
Not supported change body and header data when multi language application

### ISSUE THREAD

**Issue by h4mit** [swimlane/angular2-data-table#283]
Hi 
My application multi language supported with https://github.com/ocombe/ng2-translate angular translate for Angular 2. but not supported change body and header data when multi language application. 

```
<datatable-column name="username">
    <template let-column="column">
        {{ 'USER_LIST.username' | translate }}
    </template>
    <template let-column="value">
        {{value}}
    </template>
</datatable-column>
```
when worked init page successfully but change language not working.
****

Table version:^1.4.1

Angular version: 2.1.0

Browser: Chrome and Firefox tested

Language : TypeScript

**Comment by amcdnl** [comment]
I do not understand your question, can you make a demo?

**Comment by h4mit** [comment]
async tags don't work, tags work only in sync mode initial.

```
<datatable-column name="username">
    <template let-column="column">
        {{ 'USER_LIST.username' | translate }} <!-- don't work (async mode) -->
        USERNAME <!-- work (sync mode) -->
    </template>
    <template let-column="value">
        {{value}}
    </template>
</datatable-column>
```

**Comment by amcdnl** [comment]
This is same issue as #274, closing as dupe since its not evaluating templates correctly.
