### ISSUE TITLE
Unit tests timeout when there's a datatable in the component template

### ISSUE THREAD

**Issue by nmmarkov** [swimlane/angular2-data-table#287]
**Current behavior**
I'm trying to run jasmine unit tests for my component but if I include <datatble> in the template the tests always fail with timeout stating that "callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL". I've tried changing the default timeout but even at 10s tests still fail.

**Expected behavior**
Datatable directive should be initialized correctly when using unit tests environment

**Reproduction of the problem**
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        ReportsComponent,
        DateFormatPipe,
        mocks.MockTranslatePipe,
        mocks.MockErrorsComponent,
        mocks.MockAddReportModalComponent,
      ],
      imports: [RouterTestingModule, Angular2DataTableModule],
      providers: [
        {
          provide: ReportsService,
          useClass: mocks.MockReportsService,
        },
        TranslateService,
        {
          provide: TranslateLoader,
          useClass: mocks.MockTranslateLoader,
        },
      ],
    });
    TestBed.compileComponents();
    fixture = TestBed.createComponent(ReportsComponent);
    activatedRoute = TestBed.get(ActivatedRoute);
    helper = new TestHelper(fixture);
  }));

  it('should apply the provided filter taken from url', (done) => {
    helper.waitUntilInit().then(() => {
      expect(1).toEqual(1, '1 should be equal 1');
      done();
    });
  });

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 8.1

* **Table version:** 0.7.x
1.4.3

* **Angular version:** 2.0.x
2.0.3

* **Browser:** 
No browser -> npm test

* **Language:** 
Typescypt 2.0

**Comment by amcdnl** [comment]
Can you make a unit test that fails and PR it so I can check it out?

**Comment by nmmarkov** [comment]
Sure, here's the output:

>npm test

> anguldor@1.0.0 test
> karma start

17 11 2016 10:25:59.580:INFO [karma]: Karma v1.3.0 server started at http://127.
0.0.1:9876/
17 11 2016 10:25:59.589:INFO [launcher]: Launching browser PhantomJS with unlimi
ted concurrency
17 11 2016 10:25:59.609:INFO [launcher]: Starting browser PhantomJS
17 11 2016 10:26:08.249:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on s
ocket /#LPJAN6Jhn0AOtmBAAAAA with id 92034867
PhantomJS 2.1.1 (Windows 8 0.0.0) ReportsComponent Test1 FAILED
        Error: Timeout - Async callback was not invoked within timeout specified
 by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        Error: Timeout - Async callback was not invoked within timeout specified
 by jasmine.DEFAULT_TIMEOUT_INTERVAL.
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1 of 1 (1 FAILED) (0 secs / 10.087 s
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (5.517 secs
/ 10.087 secs)

=============================== Coverage summary ===============================

Statements   : 70.21% ( 410/584 )
Branches     : 41.43% ( 58/140 )
Functions    : 34.72% ( 50/144 )
Lines        : 70.68% ( 405/573 )
================================================================================

npm ERR! Test failed.  See above for more details.

**Comment by amcdnl** [comment]
Can you make a pull request to this repository with one of our tests failing. Once thats done, we can reopen and check it out.
