### ISSUE TITLE
Server side pagination performance issue

### ISSUE THREAD

**Issue by sorinchch** [swimlane/angular2-data-table#288]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When using pagination on the server Data Table Component expects an array of n elements and is displaying n minus page size elements. For example, page size = 10, current page is 7, array should have 70 elements and only indexes 60-69 are displayed. 

**Expected behavior**
When using pagination on server Data Table should work with an array of `[page-size]` length no matter the current page. 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
This behavior is causing performance issues with large sets of data due to creating large arrays.

**Please tell us about your environment:**

* **Table version:** 0.7.x
1.3.1

* **Angular version:** 2.0.x
2.1.1

* **Browser:** [all ]

* **Language:** [all]

**Comment by amcdnl** [comment]
It will work like this, see the https://github.com/swimlane/angular2-data-table/blob/master/demo/paging/paging-server.ts#L36-L51
