### ISSUE TITLE
template not working when using a pascal case (uppercase) field name

### ISSUE THREAD

**Issue by m3l7** [swimlane/angular2-data-table#289]
I'm using something like this:

      <datatable
          [columnMode]="'flex'"
          [rows]="devices"
          [headerHeight]="50"
          [selected]="selected"
          [scrollbarH]="true"
          [scrollbarV]="true"
          [rowHeight]="70"
          [selectionType]="'single'"
          (select)="onSelect($event)"
          class="table material fullscreen">
        <datatable-column name="Company" [flexGrow]="2">
          <template let-column="column">Azienda</template>
          <template let-value="value"> <span class="company">{{value.name}}</span></template>
        </datatable-column>
      </datatable>

the column won't output anything. The same happens if I use any field which begins with a capital letter.

using angular2-data-table 1.4.1

**Comment by amcdnl** [comment]
Use `prop`. See docs https://swimlane.gitbooks.io/angular2-data-table/content/api/column-options.html
