### ISSUE TITLE
modify template column

### ISSUE THREAD

**Issue by kanipowa** [swimlane/angular2-data-table#29]
After setting the columns  (TableColumn) from code the custom templates got lost.  ie:
```html
 <datatable-column name="Details" prop="id">
  <template let-value="value">
    <a [linkTo]="'/detail/' + value">Details</a>
   </template>
</datatable-column>
```
Anchor lost after toggling the column, based on mixing demos [toggle](https://swimlane.gitbooks.io/angular2-data-table/content/examples/column-toggle.html) and [template](https://swimlane.gitbooks.io/angular2-data-table/content/examples/expressive.html).

**Comment by amcdnl** [comment]
Interesting, you will probably not be able to mix those demos together like that. Probably best approach would be create a ngFor that adds the columns w/ the template and then toggle options in that ngFor in/out.
