### ISSUE TITLE
Selectable page size in pager

### ISSUE THREAD

**Issue by mmrath** [swimlane/angular2-data-table#290]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

There is no way to select page size

**Expected behavior**

Allow api to select page size. . The pager component take current pageSize and allowedPageSizes. When a different pageSize is selected, change event should be emitted with the new selected pageSize.

**Reproduction of the problem**

NA

**What is the motivation / use case for changing the behavior?**

Allow user to see number of records to see at a time. Some times user need to see more data than what they see usually.

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mmrath** [comment]
@amcdnl if you have any thoughts around this please let me know. I can work on this.

**Comment by amcdnl** [comment]
Is this just around the pager count or do you want the number of rows to actually be updated?

**Comment by mmrath** [comment]
With server side paging, just an event emitted when page size is choosen is enough. The actual number of rows should then be fetched and updated by client.

**Comment by amcdnl** [comment]
There is a event - https://github.com/swimlane/angular2-data-table/blob/master/demo/paging/paging-server.ts#L20 ... does this solve your request?

**Comment by mmrath** [comment]
@amcdnl the current event does not have a pageSize. I was looking for something like pageSize in the picture below. 

<img width="293" alt="screen shot 2016-11-20 at 8 58 23 am" src="https://cloud.githubusercontent.com/assets/115767/20458719/2c6b6476-af00-11e6-8663-7fee9c01a45b.png">

**Comment by amcdnl** [comment]
Why not just set this yourself in the inputs and push changes down?

**Comment by mmrath** [comment]
Yes exactly that is what I want to do. But I will have to write a custom footer in this case as the current footer does not have a page select box.

**Comment by amcdnl** [comment]
Ya, I think your best bet would be your own custom footer. 

I don't see a compelling reason for this feature in the base given the virtual pagining use case which is determined by container height. Also, many people would want a fancy select box which would add more bloat.

I could make it where you could pass a template but I think building your own is the best bet.

I'm going to close this given all this. Thanks for your suggestion and feedback.
