### ISSUE TITLE
Column display label different from column name

### ISSUE THREAD

**Issue by mmrath** [swimlane/angular2-data-table#291]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

No way to provide different column name and display label. Templates can work as a workaround but not convenient.

**Expected behavior**

We should be able to provide a display label different from column name. Because backed services send data which is closer to an identifier e.g. exchangeRate but in UI you would display it as 'Exchange Rate'.

Column name should be used to look up value for cell whereas displayLabel should be used for header.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by shattar** [comment]
Can't you use 'prop' to specify the property name.  I think what you want is already supported.

**Comment by mmrath** [comment]
Yes I think it is already supported. Just that I was not aware of it.

**Comment by vijayraghavareddy** [comment]
Can someone please explain prop with an example ?

**Comment by andrew-kuzovov** [comment]
And how to use that prop?
I'm really surprised there is no such property of ngx-datatable-column as "Label" or "Caption".
It's common scenario when you bind column to some object property and want to display other column title.

**Comment by DanielAlcaraz** [comment]
@andrew-kuzovov 

You can define an arraywith N object (1 x every row) and pass it to the columns. If you generate a custom datatable-column you can generate your column header with any value.

Object to columns property:
```
 gridColumns = [
        { id: "qa", label: "Codi", size: 1},
        { id: "rulename", label: "Nom Regla", size: 1 },
        { id: "path", label: "Camps on s'aplica", size: 2 },
        { id: "params", label: "Paràmetres de regla", size: 3 },
        { id: "criticality", label: "Criticitat", size: 1 }
   ];

```
In the `[name]` you pass the id and in the `{{ col.label }}` your custom and visible name for the column.
Component Template:
```
<ngx-datatable-column *ngFor="let col of gridColumns " [flexGrow]="col.size || 1" [name]="col.id" [sortable]="true" [canAutoResize]="true" [draggable]="true" [resizeable]="true">
            <ng-template ngx-datatable-header-template let-sort="sortFn" *ngIf="col.label">
                <span (click)="sort()">{{ col.label }}</span>
            </ng-template>
</ngx-datatable-column>
```

**Comment by hesptech** [comment]
prop usage appropriately:
           <ngx-datatable-column name="My Custom Column Header" prop="client">
            <ng-template let-value="value" ngx-datatable-cell-template>
              <strong>{{ value.clientCode }} </strong> - {{ value.clientName }}
            </ng-template>
          </ngx-datatable-column>

**Comment by hesptech** [comment]
<ngx-datatable-column name="My Custom Column Header" prop="client">
            <ng-template let-value="value" ngx-datatable-cell-template>
              <strong>{{ value.clientCode }} </strong> - {{ value.clientName }}
            </ng-template>
          </ngx-datatable-column>

**Comment by hesptech** [comment]
the above code is just to show how to use label/column-title and prop properly
