### ISSUE TITLE
Support checkbox based selection

### ISSUE THREAD

**Issue by mmrath** [swimlane/angular2-data-table#292]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Data table currently does not have checkbox based selection support

**Expected behavior**

Support checkbox based selection like https://material.google.com/components/data-tables.html#data-tables-interaction

Possibly with support for template so that it can be catered for both material and non material tables.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Ya, this is actually on my todo list :)

**Comment by Rezi** [comment]
Great to heat is on todo list. Thanks @amcdnl 

I did solve this by using template for empty column with fake checkbox like this:

```
<datatable #datatable class="material striped"
                    (activate)="onActivate($event)"
                    (select)="onSelectionChange($event)"
                    [rows]="tableRows"
                    [columns]="columns"
                    [columnMode]="'force'"
                    [headerHeight]="50"
                    [footerHeight]="50"
                    [scrollbarH]="true"
                    [selectionType]="'multi'"
                    [limit]="10"
                    [selected]="tableSelectedRows"></datatable>

                <template #checkboxTmpl let-row="row">
                    <svg class="icon-checkbox icon-checkbox-checked">
                        <use xlink:href="#icon-checkbox-checked"></use>
                    </svg>
                    <svg class="icon-checkbox icon-checkbox-unchecked">
                        <use xlink:href="#icon-checkbox-unchecked"></use>
                    </svg>
                </template>
```
Then you can show or hide the checkbox by css, based on selected row class (.active)
But there are still some drawbacks of this implementation. You cannot easily limit the selection area to this checkbox. It is switched by clicking the whole row (I would prefer if only the checkbox make the selection)

Hope it helps as temporary solution.
Templates refs can be done as described in this demo: https://github.com/swimlane/angular2-data-table/blob/master/demo/templates/template-obj.ts

**Comment by amcdnl** [comment]
Thanks! Its on my todo list soon too. The challenge you have with that is it is tricky to prevent the default clicky.

**Comment by amcdnl** [comment]
Done. 2.1.0

**Comment by RawiaAhmed** [comment]
Where I can find the sample code for it please?

**Comment by amcdnl** [comment]
See: https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.ts

**Comment by amcdnl** [comment]
The data emitted is immutable, so you can always compare.

**Comment by RawiaAhmed** [comment]
yea right thanks 👍

**Comment by touqeershafi** [comment]
Link is broken: 
> See: https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.ts

can i use custom template for checkbox ?

**Comment by alandykes** [comment]
Looks like the link should be [https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.component.ts](https://github.com/swimlane/ngx-datatable/blob/master/demo/selection/selection-chkbox.component.ts)

**Comment by nhducseuit** [comment]
How do I toggle between checkbox selection and single row selection? I don't think it work now, tried with changing selectionType, headerCheckboxable, checkboxable

**Comment by ShinDarth** [comment]
from the documentation it is not clear how to achieve this

**Comment by nhducseuit** [comment]
@ShinDarth  have you checked the above ts file?
The key is to set value of [selectionType]="'checkbox'"
That will result in default checkbox selection mode with a checkbox created by an <input type="checkbox"> element.
In order to customize the checkbox element on your own, put the customized checkbox element into <ng-template> and place it as child of <ngx-datatable-column> tag.

**Comment by ShinDarth** [comment]
@nhducseuit yes I understood how to achieve it from the example source file above. I think it should be included in the documentation.
