### ISSUE TITLE
ngif not working in template

### ISSUE THREAD

**Issue by jibhey** [swimlane/angular2-data-table#295]
Hi again,

I want to use template in cell. I need to use ngif but it not working. the Template is in the html component file and it look like this :

`<template #cellTpl let-column="column" let-row="row" let-value="value" let-i="index">
    <div *ngif="column.wa_status != undefined && column.wa_status == 1" class="cell-status-1">
        {{value}}
    </div>
    <div *ngif="column.wa_status != undefined && column.wa_status == 2" class="cell-status-2">
        {{value}}
    </div>
    <div *ngif="column.wa_status != undefined && column.wa_status == 3" class="cell-status-3">
        {{value}}
    </div>
    <div *ngif="column.wa_status != undefined && column.wa_status == 4" class="cell-status-4">
        {{value}}
    </div>
</template>`

Chrome log this error :
`Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngif' since it isn't a known property of 'div'. ("

<template #cellTpl let-column="column" let-row="row" let-value="value" let-i="index">
    <div [ERROR ->]*ngif="column.wa_status != undefined && column.wa_status == 1" class="cell-status-1">
        {{valu"): MdsapDatatableComponent@17:9
Property binding ngif not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("

...

`

regards,

**Comment by Bigismall** [comment]
use *ngIf instead of *ngif

18 lis 2016 5:08 PM "jibhey" <notifications@github.com> napisał(a):

**Comment by jibhey** [comment]
ooh ! ok, bad mistake after a long working day. sorry for this :)

**Comment by Bigismall** [comment]
so @jibhey  please close issue
