### ISSUE TITLE
$$index bug on server sierve-side paging

### ISSUE THREAD

**Issue by Kopleman** [swimlane/angular2-data-table#299]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Something changes $$index inside array for rows on server-side paging. On first load of page everything is ok, but when u return to it the order of rows changes. 

**Expected behavior**
The order of rows doesnt change on page change.
**Reproduction of the problem**
http://plnkr.co/edit/XXiJfDDKxLv3X7IT0QQa?p=preview

or server-paging in demos

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 
1.7.0

* **Angular version:** 
2.2.0

* **Browser:**
all 

* **Language:** 
TypeScript 2.1.1

**Comment by vertil** [comment]
Hi there

Also reproducable in your own [Demo](http://swimlane.github.io/angular2-data-table/).
Just click on a page which you didn't already load and its preavious page isn't already loaded, too.

Example:
You start on page 1 -> click page 3 -> no data shown
Back to page 1 -> click page 2 -> click page 3 -> data shown

kr
Ales

**Comment by Kopleman** [comment]
Also there is quite strange behaiviour in how we add new rows in array. In examples(my and default) we use spread operator(`[...array]`)( or we can use Lodash's `.deepClone()`) and it will show pages but with bug that mentioned above. If we add rows dirrectly `$$index` is ok, but pages dont show any data on first load(you need to go back and return). Here is [plunk](http://plnkr.co/edit/k3COCrG67sqoIZTlew70?p=preview)

**Comment by ocombe** [comment]
Yes I have the same problem when I try to change the order of the rows using array.sort and the spread operator (to trigger the @input), the order of the news rows is changed but not like it should (it's not showing the order of the rows that I sent)...
I logged the rows after updating them, the first one is $$index = 1, the second one has no $$index, the third is $$index = 2...

![rows](https://cloud.githubusercontent.com/assets/265378/20594852/032118e6-b238-11e6-9d29-db62f103a63e.PNG)

And for some reason the row 1647 is $$index = 4... (which is the same $$index as row 5)

![rows2](https://cloud.githubusercontent.com/assets/265378/20594896/27df5b5c-b238-11e6-8ea9-1ecc6180da74.PNG)

**Comment by ocombe** [comment]
I did a revert to 1.5.1 that worked fine, it's 1.6.0 that introduced the bug

**Comment by amcdnl** [comment]
@ocombe  - any ideas what caused it?

**Comment by ocombe** [comment]
No, I haven't took time to investigate, but it's in the 1.6.0 release :)

**Comment by ocombe** [comment]
The bug is fixed for me in 2.1.3, not sure in which version you've fixed it, but it works now

**Comment by stefmabo** [comment]
When I show data list thought a Web Service, it only load data by "offset" if the Web Service support pagination. 
I think the implementation of this datatable is based giving JSON file.

If we need to call a Web Service to show the data, the `this.indexes.first` would be always 0, because the data loaded by Web Service always start in index 0.

Then I commented this line of code `//first = Math.max(this.offset * this.pageSize, 0);`
In my case, I never load the data using JSON file.

```
updateIndexes(): void {
    let first = 0;
    let last = 0;

    if (this.scrollbarV) {
      // Calculation of the first and last indexes will be based on where the
      // scrollY position would be at.  The last index would be the one
      // that shows up inside the view port the last.
      const height = parseInt(this.bodyHeight, 0);
      first = this.rowHeightsCache.getRowIndex(this.offsetY);
      last = this.rowHeightsCache.getRowIndex(height + this.offsetY) + 1;
    } else {
      //first = Math.max(this.offset * this.pageSize, 0);
      last = Math.min((first + this.pageSize), this.rowCount);
    }

    this.indexes = { first, last };
  }
```

Then in the component add this.

1. ngOnInit()

```
ngOnInit() {
    this.page();
}
```

2. page()

```
page() {
    this.fetch((results) => {
      this.count = results.total; // Web service give me the total
      this.rows = results.list; //Web Service give me the data
    });
}
```

3. fetch() 

```
fetch(cb) {
    this.callService.list('url', this.offset, this.limit).subscribe(
      data=> {
        cb(data);
      },
      null,
      () => {

      }
    );
}
```

4. OnPage()

```
onPage(event) {
    this.offset = event.offset;
    this.page();
}
```

**Comment by stefmabo** [comment]
When I show data list thought a Web Service, it only loads data by **offset** and **limit** if the Web Service supports pagination. 
I think the implementation of this datatable is based giving JSON file.

If we need to call a Web Service to show the data, the `this.indexes.first` would be always 0, because the data loaded by Web Service always start in index 0.

Then I commented this line of code `//first = Math.max(this.offset * this.pageSize, 0);`
In my case, I never load the data using JSON file.

**Go into the ngx-datatable app and edit updateIndexes()**

```
updateIndexes(): void {
    let first = 0;
    let last = 0;

    if (this.scrollbarV) {
      // Calculation of the first and last indexes will be based on where the
      // scrollY position would be at.  The last index would be the one
      // that shows up inside the view port the last.
      const height = parseInt(this.bodyHeight, 0);
      first = this.rowHeightsCache.getRowIndex(this.offsetY);
      last = this.rowHeightsCache.getRowIndex(height + this.offsetY) + 1;
    } else {
      //first = Math.max(this.offset * this.pageSize, 0);
      last = Math.min((first + this.pageSize), this.rowCount);
    }

    this.indexes = { first, last };
  }
```

Then in the component add this.

**1. ngOnInit()**

```
ngOnInit() {
    this.fetch();
}
```


**2. fetch()** 

```
fetch(event?) {
    if(event) this.offset = event.offset;
    this.callService.list('url', this.offset, this.limit).subscribe(
      data => {
        this.count = data.total; //Web Service gives me the total
        this.rows = data.list; //Web Service gives me the data
      },
      null,
      () => {

      }
    );
}
```

**3. ngx-datatable tag**

```
<ngx-datatable
        class="material"
        ...
        (page)='fetch($event)'> <!--Here--> ...
</ngx-datatable>
```
