### ISSUE TITLE
adjust columns on different columns

### ISSUE THREAD

**Issue by kaloczidev** [swimlane/angular2-data-table#30]
Setting the table cols trough `dataTableOptions.columns` doesn't trigger the resizing method when the array's length doesn't change.

ie:
 4 columns `[a,b,c,d]`, all have the `canAutoResize: true` property and have different widths.
Load the first 2 columns(`a` and `b`). Then set to show `b` and `c` columns to show.. their width became the default width - causes free space in the table.

**Comment by amcdnl** [comment]
Closing as this is not relevant anymore w/ OnPush
