### ISSUE TITLE
default sort not working with comparator

### ISSUE THREAD

**Issue by morriq** [swimlane/angular2-data-table#300]
comparator is executed only from manual click.

check this out http://plnkr.co/edit/IzSM9sqaomnTJFbw44gw?p=preview

**Comment by benjamincharity** [comment]
In my (small and recent) experience, the default sort only seems to affect the UI; not the actual order of the rows.

Even when not using a comparator, the table isn't sorted on load. Only after the user clicks the column header.

**Comment by amcdnl** [comment]
Yes, you have to pass your sort you wish to use. If you do that it will auto sort them.

**Comment by RicardoVaranda** [comment]
I am having the exact same issue @amcdnl Are you able to expand on what you mean by needing to pass sort?
