### ISSUE TITLE
Inline edit edits wrong values

### ISSUE THREAD

**Issue by paweldziura** [swimlane/angular2-data-table#301]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Inline edit works in wrong way. Editing first element edits second (works like that even in a demo) and is totaly broken when sorted values.
When console logged rows, it seems that some of them have row.$$index and some not. In demo there is row.$$index used to navigate through array.

**Expected behavior**
Inline edit should edit proper cells.

**Reproduction of the problem**
double click on a first cell and blur the input.
sort and try to edit some values

**Please tell us about your environment:**
Windows 10 / Chrome v54

* **Table version:** 0.7.x
1.7

* **Angular version:** 2.0.x
2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 54

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by paweldziura** [comment]
There is an error in demo page but it's possible to manage it using "row.yourproperty" field

**Comment by kippmr** [comment]
Saw this post when looking up the error that is still present on the demo page with inline editing and sorting, how did you use the 'row.yourproperty' field to fix the bug?

**Comment by slang1** [comment]
to fixed this issue should:
* **override this class:**
.datatable-body-cell-label{
    width:100% ;
    height:100%;
}
***add class to the element with this css:**
.display-element{
    display: inline-block;
    width: 100%;
    height:100%;
}

**Comment by thariel** [comment]
The error is still present in demo page. How to fix this issue?

**Comment by AcidAndroid** [comment]
I have the same issue. How did you solve it???

> There is an error in demo page but it's possible to manage it using "row.yourproperty" field

I have the same issue. How did you solve it using "row.yourproperty"?

**Comment by bisht006** [comment]
Hi I am having the same issue is there any update on this? I have tried both the solutions but didn't work. And how to use row.yourproperty ?
