### ISSUE TITLE
datatable-colum header/cell template

### ISSUE THREAD

**Issue by ghetolay** [swimlane/angular2-data-table#304]
I was checking the code and came across this on [column.directive.ts](https://github.com/swimlane/angular2-data-table/blob/master/src/components/column.directive.ts) : 

```ts
 get hasHeaderTemplate() {
    // this is a tad nasty but can't think of a better way
    // to differate if the prop is header vs cell
    return this.templates.length === 2;
  }
```

I think you can use reference like so 

```ts
@Directive({ .. })
export class DataTableColumnDirective {
    @ContentChild('header') headerTemplate: TemplateRef;
    @ContentChild('cell') cellTemplate: TemplateRef;
}
```

and using it like : 
```
<datatable-column>
    <template #header>
        ...
    </template>
    <template #cell>
        ....
    </template>
</datatable-column>
```

Possible downside is that he cell reference `#cell` becomes mandatory.

**Comment by amcdnl** [comment]
Ya, I'm working on a better approach for this. Here is a SO post I've been asking people for feedback on: http://stackoverflow.com/questions/40692955/angular2-templateref-selector

**Comment by ghetolay** [comment]
I like more the template + directive because `<datable-column>` feel like a component and it was confusing at first. While I think `<template column>` says it all : we are defining the column template and we can use the directive into `@ContentChildren()` to select template.
Now the real problem with this is context var i.e. `let-value="value"`. User shouldn't have to do that.

**Comment by amcdnl** [comment]
Fixed in master, will be released soon.
