### ISSUE TITLE
Sorting formatted numbers.

### ISSUE THREAD

**Issue by compitDanielos** [swimlane/angular2-data-table#305]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
```
TableData = {
    data:[
        {id:1, price:1900000, displayPrice:'$1.9M'}
        {id:2, price:990000, displayPrice:'$990K'}
    ]
}
```

**Expected behavior**
Displaying 'displayPrice' prop, but sorting on 'price' prop.

**What is the motivation / use case for changing the behavior?**
Ability to load preformatted data, and do not format on fly

* **Table version:** 1.7.0

* **Angular version:** 2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by amcdnl** [comment]
You can pass your own sorting comparer to handle these type of specific sorts - https://github.com/swimlane/angular2-data-table/blob/master/demo/sorting/sorting-comparator.ts

**Comment by madebysoren** [comment]
Hi @amcdnl,

How can I accomplish this in template syntax?

component.html:
`
      <ngx-datatable-column name="Expires" [comparator]="comparatorDate" [flexGrow]="1" [draggable]="false">
        <ng-template let-value="value" let-row="row" ngx-datatable-cell-template>
          {{ row.ExpirationDate | amTimeAgo }}
        </ng-template>
      </ngx-datatable-column>`

component.ts:
`comparatorDate(a: any, b: any) {
    if (a.valueOf() < b.valueOf())  {
      return -1;
    }
    return 1;
  }`

When debugging this, a and b are empty strings.

/ Søren
