### ISSUE TITLE
[columnMode=force] column overflow

### ISSUE THREAD

**Issue by ghetolay** [swimlane/angular2-data-table#309]
**I'm submitting a ...**
```
[X] bug report
```

**Current behavior**
When using force columnMode, in case where some column have float width, inner div of `datatable-header`  and `datatable-scroll` have smaller width than the datatable while columns fit perfectly the width of datatable. This makes columns to overflow.

**Expected behavior**
Columns should fit into their parents.

**Reproduction of the problem**
Create a datable with a width of 1000px for example and 3 columns.
Each column will have a width of 333.3333px and inner div of `datatable-header` and `datatable-scroll` will have a width of 999px.

https://plnkr.co/edit/DQLnDgwXSGLAcEPJTGot?p=preview

**Origin of problem**
I think the problem is that [columnTotalWidth()](https://github.com/swimlane/angular2-data-table/blob/master/src/utils/column.ts#L46) is doing a `parseInt()` on the column's width while it's a float value.

**Possible solution**
Removing the `parseInt()` (in my tests column's width was always a number) or replacing with a `parseFloat()` works for me.

* **Table version:** 1.7.0

* **Angular version:** 2.0.x

* **Browser:** [all]

* **Language:** [all]

**Comment by amcdnl** [comment]
If you wanna make a PR to update to a float, that would be great!

**Comment by ghetolay** [comment]
While I was doing the PR I found that there is 2 function that compute total width of columns : 

- `columnTotalWidth(columns, prop?)` that'll use a `parseInt()`
- `columnsTotalWidth(columns: any, prop?: any)` which seems to a copy of the first without the `parseInt()`

Maybe instead of using `parseFloat()` the solution it to use `columnsTotalWidth()` instead of `columnTotalWidth()` and do the `parseFloat()` on `setColumnDefaults()` which seems to normalize the column object. 

I'm taking as an assumption that `column.width` can only be a string when it's passed as an input by the user. If there is more scenario the solution will probably not work.
