### ISSUE TITLE
How to Display multiple data in a column of a datagrid row?

### ISSUE THREAD

**Issue by vibingopal** [swimlane/angular2-data-table#310]
Hi Team,

I am using angular 2 with type script for my application and i struck with the functionality on how to display multiple data values in the data grid column of a datagrid row.

For example : iam getting list of values for a particular column from server, now because of the prop attribute in typescript, we can map only one value. But how to map multiple values for a particular column .
Type script :
 new TableColumn({ name: 'Primary',prop:'primaryRole.stationCode')

I need to use primaryRole.name, primaryRole.details in the above prop value. How it can be done using datatable .

Thanks

**Comment by amcdnl** [comment]
Check out templates - https://github.com/swimlane/angular2-data-table/blob/master/demo/templates/template-dom.ts
