### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by daniele-zurico** [swimlane/angular2-data-table#315]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

The data table is amazing tool but I would to *export* the data present in csv or something else instead to use another plugin to do that

**Comment by amcdnl** [comment]
Thanks for your suggestion but this is not something we are looking to add. Watch the video or check out the Architecture docs for more info.

**Comment by buctwbzs** [comment]
i think many people like need export data.

**Comment by unsafecode** [comment]
Count me in: we had to rebuild this feature from scratch, which is very inconvient....

**Comment by guillaumegarcia13** [comment]
Please, check this it might help: https://github.com/swimlane/ngx-datatable/issues/809#issuecomment-332842776

**Comment by sw-tracker** [comment]
+1 I would also love to have this feature!
