### ISSUE TITLE
Table not responsive with flexbox

### ISSUE THREAD

**Issue by web265p3** [swimlane/angular2-data-table#316]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I want the datatable to fit in my responsive UI-Design, so I give it a width of 100%. However - inside the table there are a lot of elements which exceed the 100% with an automatically set inline width. This inline width seems to be set when the table component loads, but is not updated on window-resize.
So if I want to use the following markup and then I drag the browser window small, the table does not get small as well:

```
    <div style="display: flex; flex-direction: row; ">
        <div style="flex-basis: 200px; flex-grow: 1; flex-shrink: 1;">

    
        </div>
        <div style="flex-basis: 600px; flex-grow: 1; flex-shrink:1;">
            <datatable 
                class="material datatable fixed-header fixed-row scroll-vertical"
                [rows]="rows"
                [columns]="columns"
                [columnMode]="'force'"
                [headerHeight]="50"
                [footerHeight]="50"
                [rowHeight]="50"
                [sortType]="'multi'"
                [limit]="7">            
            <datatable-column name="Id" [width]="10"></datatable-column>
            <datatable-column name="Name" [width]="20"></datatable-column>
            </datatable>
        </div>
    </div>
```
If I press F5 with my small window, after reload the table has an appropriate width. 

**Expected behavior**
Table with a width of 100% should always have a maximum size of 100%, not more or less.

**Reproduction of the problem**
Just copy my markup and use the table. With a big browser window load the page. Then drag the browser smaller until you see, that the table does not get smaller and you see a horizontal scroll bar.
Press F5 while the window is small. The scroll bar disappears and everything seems to be nice.

**Comment by fenta23** [comment]
Have seen the same. I use flex columnMode an there it seems to be fine. 
In Addition i use table.recalculate() after resizing the window.

So i think it's just a workaround, but works for the moment.

**Comment by amcdnl** [comment]
There is no DOM specific handler for resizing ( that isn't a mega hack lol ). We listen for window resizes but if your elements are resizing internally, you will need to tell the table to update itself. I'm open to suggestions about making a cleaner API to do this if thats something you think would help?
