### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by web265p3** [swimlane/angular2-data-table#317]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently there is no right-click context menu available. Any proposals how you handle this kind of necessity?

**Comment by amcdnl** [comment]
You can accomplish this with column templates very easily. See our manifesto in the Architecture docs page for more info.
