### ISSUE TITLE
Change name to ng-data-table

### ISSUE THREAD

**Issue by mmrath** [swimlane/angular2-data-table#320]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[*] feature request
[ ] support request => Please do not submit support request here
```
Now that angular is following semver, I think we will soon have angular 3. It would nice to rename this project to ng-data-table or something on that line. I know this is a breaking change, but nice to do it earlier.

**Comment by amcdnl** [comment]
ng-data-table is a anti pattern name since it starts with ng...generally that's reserved for angular framework names.

On the flip side, @brocco told me that there is some AoT issues with a single name directive so it does need to change, I just don't know what I want to change it to.

**Comment by mmrath** [comment]
May be something like sm-data-table or sl-data-table?

**Comment by amcdnl** [comment]
Ya, I was thinking `swui-data-table` or `swui-datatable` playing off https://github.com/swimlane/swui

**Comment by mmrath** [comment]
May be just SW instead of SWUI. Just a personal preference for shorter code.

**Comment by Brocco** [comment]
I completely agree with the idea of renaming the lib. My suggestion for names in no particular order:

- swui-data-table
- swui-datatable
- sl-data-table
- sl-datatable
- swui-grid
- sl-grid
- panda-grid

**Comment by istiti** [comment]
Panda-grid is my favorite

**Comment by amcdnl** [comment]
Prob gonna do `swui-datatable` ... ppl gonna hate me for changing this haha

**Comment by Brocco** [comment]
You can leave both there for a while by specifying both selectors, but announce the change and planned deprecation.

**Comment by amcdnl** [comment]
Fixed in master, will be released soon.
