### ISSUE TITLE
doesn't work on webpack?

### ISSUE THREAD

**Issue by lilithaileron** [swimlane/angular2-data-table#323]
I've checked the previous issues and can't find the correct answer. how do you import this on webpack? I'm using your latest release, (just installed it today) my node version is 6.9.1, npm 3.10.8. 

Here's what I did:
1. installed via npm
2. put import { Angular2DataTableModule } from 'angular2-data-table'; in my app.module
3. put Angular2DataTableModule in the list of imports:[]

Is there anything else that I need to do/define? or is the import above wrong?

Thank you

**Comment by lilithaileron** [comment]
sorry it seems to be working now

**Comment by AGoodnight** [comment]
what fixed it?

**Comment by teddywest32** [comment]
@lilithaileron @AGoodnight have you found out what solves the issue?

**Comment by amcdnl** [comment]
I used it in webpack in all my projects so not sure what you guys having issues w/
