### ISSUE TITLE
Where is the refresh() method?

### ISSUE THREAD

**Issue by cortopy** [swimlane/angular2-data-table#329]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
According to the [docs](https://github.com/swimlane/angular2-data-table/blob/065b439db23a95b2cc7ed62e8a9100eba942f15c/docs/api/table-fns.md) there is a method called `refresh()` that refreshes the rows in the grid.

However, my `DatatableComponent` doesn't have any such method. A quick search on the repo yields zero results too.

**Expected behavior**
Currently cells are not being updated on external events. User has to click on the table to trigger rerendering of the row. Being able to refresh the table's view would be ideal.

**Comment by istiti** [comment]
Refresh will be delete! Certainly. We wait until @austin fix something

**Comment by amcdnl** [comment]
Opps... Forgot to remove from docs. See #255 for info on this.
