### ISSUE TITLE
how to use this with bootstrap classes??

### ISSUE THREAD

**Issue by kushwahashiv** [swimlane/angular2-data-table#335]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
U want it to look like bootstrap table?

**Comment by kushwahashiv** [comment]
@amcdnl  I'm trying to use bootstrap classes (i.e ```table```) with datatable earlier it was pretty easy to use with version 1.7 but not sure how to sue with 2.0.

**Comment by amcdnl** [comment]
Should be very similar. Nothing has change via CSS much.
