### ISSUE TITLE
Datatable shows only a single scrollable row

### ISSUE THREAD

**Issue by damnko** [swimlane/angular2-data-table#337]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
The scrollable datatable shows only one line of data

**Reproduction of the problem**
I have created a new empty project with angular-cli version 1.0.0-beta.19-3 and followed the instructions on https://swimlane.gitbooks.io/angular2-data-table/content/introduction/installing.html to install the module so:

1. added the `Angular2DataTableModule` to `app.module.ts`
2. imported `datatable.css` and `material.css` into the main `styles.css` file
3. copied the whole code in https://github.com/swimlane/angular2-data-table/blob/master/demo/basic/scrolling.ts inside `app.component.ts` only pointing to a local copy of `100k.json`

But the table only shows one scrollable row of data (screenshot here: http://imgur.com/RHHHUc2). So all the data is there but the visible area is just that single line.

The sample project can be found here: https://github.com/damnko/data-table-test

**Comment by amcdnl** [comment]
Did you set a defined height of the container element? Using virtutual scrolling you must have a fixed height for it to measure avail;able viewport space. Let me know if that works, closing this for now.
