### ISSUE TITLE
Errors: Cannot read property X of undefined - 2.1.x

### ISSUE THREAD

**Issue by benjamincharity** [swimlane/angular2-data-table#339]
**I'm submitting a ...**

- [x] bug report

**Current behavior**

Tests throw many Datatable errors:

![google chrome - travis-ci com - - screen shot dec 2 2016 4 00 30 pm](https://cloud.githubusercontent.com/assets/270193/20850428/20d39d4c-b8a9-11e6-9a0a-44e3b9ad80f6.png)

Primary errors:

- `Error: Error in ./DatatableComponent class DatatableComponent - inline template:15:8 caused by: Cannot read property 'length' of undefined`
- `Error: Error in ./DataTableHeaderComponent class DataTableHeaderComponent - inline template:6:6 caused by: Cannot read property 'forEach' of undefined`

**Expected behavior**

Tests should run as they did in 2.0.0

**Reproduction of the problem**

- Upgrade to `.2.1.x`.
- Run your tests.

Downgrading back to `2.0.0` solves the issue.

**Please tell us about your environment:**

This happens locally:

- NPM / OSX / Karma / angular-cli

And also happens on TravisCI (linux) (see screenshot above)

***Table version:** 2.1.x

***Angular version:** 2.2.4

***Browser:** Chrome

***Language:** TypeScript 2.1.1

---

Not sure if the upgrade is simply exposing something erroneous in my own code or if it truly is the new Datatable code.

---

> Edit

Just noticed that the errors are being thrown during the build also (not just during testing):

![google chrome - remedy-admin benjamincharity work - - screen shot dec 2 2016 4 47 03 pm](https://cloud.githubusercontent.com/assets/270193/20851523/0a63daf8-b8af-11e6-8563-77d7507fa4b4.png)

**Comment by amcdnl** [comment]
Travis says its passing....Any ideas why it would be different?

**Comment by amcdnl** [comment]
Closing this, workings correctly in latest.
