### ISSUE TITLE
Naming consistency Datatable vs DataTable

### ISSUE THREAD

**Issue by mmrath** [swimlane/angular2-data-table#341]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
I see that in some places Datatable is used and other places it is DataTable (two words). I think it would be nice to make it consistent. Also the directive and component selectors should follow this, ie (swui-datatable -> Datatable or swui-data-table -> DataTable). Some IDEs show Datatable is not a word so it would be nice to use DataTable.

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Thanks, I really hate to do another breaking change so quickly lol. I considered making it like this but to keep things shorter I decided against it. I'd like to hear others feedback before merging this.
