### ISSUE TITLE
Data only shown after window resize when using externalPaging

### ISSUE THREAD

**Issue by TheBurgerShot** [swimlane/angular2-data-table#344]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Data is only shown after resizing the window. As far as I know this is only a problem when using external paging.

I am using these settings:

`<datatable
  class="material striped fill-width"
  [rows]="publications"
  [columnMode]="'force'"
  [headerHeight]="50"
  [footerHeight]="50"
  [rowHeight]="'auto'"
  [externalPaging]="true"
  [limit]="limit"
  [count]="count"
  [offset]="0"
  [scrollbarH]="true"
  (page)='onPage($event)'>`

![screenrecording](https://cloud.githubusercontent.com/assets/5908466/20861240/3c8cc102-b98b-11e6-9713-e972103ebcaf.gif)

**Expected behavior**
The data to be shown without the requirement to resize the screen first.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
This is not a good user experience :)

**My environment:**
OS X 10.12.1 (Sierra)

* **Table version:** 1.7.0

* **Angular version:** 2.2.4

* **Browser:** [all | **Chrome XX** | Firefox XX | IE XX | **Safari** | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [**all** | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Can you make a plunkr showing this? I have not encountered it.

**Comment by amcdnl** [comment]
Plz retry in 2.1.2

**Comment by TheBurgerShot** [comment]
@amcdnl It is fixed! Thank you!

**Comment by amcdnl** [comment]
Great to hear! Thanks!

**Comment by CleberPinheiroRamos** [comment]
@TheBurgerShot resolvido em https://github.com/swimlane/ngx-datatable/issues/761
