### ISSUE TITLE
datatable-column not working as expected

### ISSUE THREAD

**Issue by camberos** [swimlane/angular2-data-table#346]
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
At the moment I am trying to populate the data table from a GET result, the objects are ok, as shown in the image below.

![screen shot 2016-12-06 at 12 47 25 pm](https://cloud.githubusercontent.com/assets/1689444/20910111/b3d84c3e-bbb3-11e6-81bb-684ac4ff0a07.png)

Once I add a third column with an underscore in the key, is where it gets ugly. As shown in the screenshot. For example the value **group_id**

![screen shot 2016-12-06 at 1 00 09 pm](https://cloud.githubusercontent.com/assets/1689444/20910171/f64fe036-bbb3-11e6-861a-95807ac85317.png)

This is the output, showing the missing column. 

![screen shot 2016-12-06 at 12 52 10 pm](https://cloud.githubusercontent.com/assets/1689444/20910086/8b0fae78-bbb3-11e6-97df-aad0e895c213.png)

**Expected behavior**
The expected behaviour should be as simple as shown in the code. Add  a datatable-column with some basic parameters and should work, unless I am missing something in the configuration. 

* **Angular version:** 2.2.3

* **Browser:** Chrome Version 54.0.2840.98 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
You need to use `prop` instead of `name`.

**Comment by kuncevic** [comment]
Just being caught by that having the underscore in the json prop. Why it is like that? Any more details?
