### ISSUE TITLE
add a CHANGELOG

### ISSUE THREAD

**Issue by cortopy** [swimlane/angular2-data-table#351]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

I've tried to upgrade from 1.7 to 2.1.3 but this broke all my table. Realising the selectors had changed was easy, but my templates have stopped rendering and I can't work out why.

Would it be possible to have a list of changes for major version changes, even if it's a summary of the most important changes only?

**Comment by amcdnl** [comment]
docs/changelog.md
