### ISSUE TITLE
Specify custom CSS classes on table cells using expressive templates

### ISSUE THREAD

**Issue by IRCraziestTaxi** [swimlane/angular2-data-table#354]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Cannot find a means of adding a CSS class to a datatable-body-cell using expressive body cell templates.

**Expected behavior**

Would like to be able to add a CSS class to a datatable-body-cell using expressive body cell templates.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

I need to allow overflow to be visible on cells in just one column.

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gearsandcode** [comment]
Check out: https://github.com/swimlane/angular2-data-table/blob/master/demo/templates/template-obj.ts#L22 for an idea of how to do this.

**TemplateRef via Column Property**
Demo is here under Templates > TemplateRef: http://swimlane.github.io/angular2-data-table/#

**Comment by IRCraziestTaxi** [comment]
Thank you for the reply, but I'm not seeing how that allows me to add a class to the generated body cell itself. The generated datatable-body-cell element is the element to which overflow hidden is applied, so setting overflow visible to an element inside of that generated cell won't do me any good.

**Comment by gearsandcode** [comment]
This is a css issue, not an issue with this table. Apply the class to the column cells you need to not be overflow:hidden;

This post explains how to make the cells run past the parents boundary: http://front-back.com/how-to-make-absolute-positioned-elements-overlap-their-overflow-hidden-parent
