### ISSUE TITLE
Reference to row object with prop 

### ISSUE THREAD

**Issue by m3l7** [swimlane/angular2-data-table#361]
If I define the columns templates within the html (inline) I can access the row object by using prop="".
However, if I define the columns imperatively with TemplateRef, this trick doesn't work anymore. Is there an alternative way?

**Comment by Thoma5** [comment]
You mean something like   `<template let-row="row" let-value="value" swui-datatable-cell-template>` ? 
Then you can easily access row with `row`.

**Comment by m3l7** [comment]
yeah.. that did the trick.
thanks!
