### ISSUE TITLE
Pagination icons are missed on a brand new setup

### ISSUE THREAD

**Issue by TakhirMamirov** [swimlane/angular2-data-table#364]
Grabbed latest release and installed. Added two css references to datatable and material css. Run successfully, but the bottom pagination icons are missed. Neither left or right, nor back to beginning or to end. What am I missing?

**Comment by Thoma5** [comment]
You need to specify them yourself. This can be done with  e.g. `[cssClasses]="iconCss"` Attribute in the template and 
` iconsCss = {
    sortAscending: 'glyphicon glyphicon-chevron-down',
    sortDescending: 'glyphicon glyphicon-chevron-up',
    pagerLeftArrow: 'glyphicon glyphicon-chevron-left',
    pagerRightArrow: 'glyphicon glyphicon-chevron-right',
    pagerPrevious: 'glyphicon glyphicon-backward',
    pagerNext: 'glyphicon glyphicon-forward'
  };`
in your code.

**Comment by TakhirMamirov** [comment]
Thank you!

**Comment by nsuhanshetty** [comment]
@Thoma5 **[cssClasses]="iconCss"** must updated to **[cssClasses]="iconsCss"**
