### ISSUE TITLE
Data not rendering

### ISSUE THREAD

**Issue by murac** [swimlane/angular2-data-table#46]
Hello!

I'm having a problem where my data is show up blank in the table. The columns are displaying correctly, however. When using the dummy data in the documentation everything works, but when I switch to mine, no luck. I've console.logged both data sets and they are both arrays of objects. The datatable is using pagination and displays the correct count and number of pages. I'm importing a csv file and building the array that way. I thought it might have been spaces in the columns, but that wasn't the case. 
![image](https://cloud.githubusercontent.com/assets/9281386/17502200/f280391e-5db3-11e6-9286-243560e4a080.png) <-- test data
https://files.gitter.im/swimlane/angular2-data-table/OSlA/blob
![image](https://cloud.githubusercontent.com/assets/9281386/17502207/03c674b8-5db4-11e6-98a7-8fd5160d362c.png) <--- mine
![image](https://cloud.githubusercontent.com/assets/9281386/17502217/0f78471e-5db4-11e6-835c-d9d166324f82.png)

The code is straight from the docs. What's going on here? Thanks for the help!

**Comment by amcdnl** [comment]
Can you post a demo plunkr?

**Comment by murac** [comment]
Ok here we go. I managed to modify one of yours from the docs.

https://gist.run/?id=1dd2022892e239279f63ec6050ac7f0d

I provided the test.csv file you'll have to save it to your computer to import it, however. Thank you, thank you for your help!

**Comment by murac** [comment]
Ok, figured it out. Moral of the story: set a "prop" value when building the TableColumn object.

**Comment by amcdnl** [comment]
Glad to hear you got it, sorry didn't get to it sooo busy! 

I'm gonna make that example u posted part of demos! Thanks for sharing!

**Comment by murac** [comment]
Go for it.
No offence taken, I just needed some time to let it all simmer. But this means I won't feel bad for pestering you next time!

**Comment by mmansouri** [comment]
Hello @murac ,
I have the same issue but i didn't undrestand:  "set a "prop" value when building the TableColumn object."
Can you explain please.
Thank you

**Comment by anitalpatil** [comment]
Even I have same kinda issue murac for ngx-datatable to render the row data getting the data in the form of object, if i display data in front end with property binding to json am able to display in json format, but not in data table.... have you got solution for it?

**Comment by Sebubu** [comment]
+1

**Comment by atiquevevegum** [comment]
Did you guyz got any help.   Even I am also getting the same issue. while calling 

**test.ts**
rowselect = [
    { company: 'Austin', country: 'Male', industry: 'Swimlane' },
    { company: 'Austin', country: 'Male', industry: 'Swimlane' },
  ];
 selected: any[] = [];
  rows = [
  ];
  columns = [
    { prop: 'company' },
    { name: 'country' },
    { name: 'industry' }
  ];
 
for(let i = 0; i < this.total_searches; i++) {
                  //For Table Data
                  this.rows.push({
                        "company": this.result[i]._source.COMPANY_NAME,
                        "country": this.result[i]._source.COUNTRY_NAME,
                        "industry": this.result[i]._source.INDUSTRY_TYPE
                   });   
}


**html**

<ngx-datatable
          style="width: 105%;height: 100%"
          class="material"
          [rows]="rows"
          [columnMode]="'force'"
          [headerHeight]="50"
          [footerHeight]="50"
          [rowHeight]="'auto'"
          [limit]="10"
          [selected]="selected"
          [selectionType]="'checkbox'"
          [selectAllRowsOnPage]="false"
          [displayCheck]="displayCheck"
          (activate)="onActivate($event)"
          (select)='onSelect($event)'>
          <ngx-datatable-column
            [width]="40"
            [sortable]="false"
            [canAutoResize]="false"
            [draggable]="false"
            [resizeable]="false"
            [headerCheckboxable]="true"
            [checkboxable]="true">
          </ngx-datatable-column>
          <ngx-datatable-column name="Company"></ngx-datatable-column>
          <ngx-datatable-column name="Country"></ngx-datatable-column>
          <ngx-datatable-column name="Industry"></ngx-datatable-column>
        </ngx-datatable>



I got the data if I pull from rowselect, but I didn't get the data if I pull from rows array. Both structure are same. But I got the count. Still no data display.

Any help?

**Comment by anitalpatil** [comment]
@atiquevevegum  For listing employee I wrote code as follows may be it will help you
In HTML 

`<ngx-datatable   
class='material'
[columns]="columns"
[columnMode]="'force'"
[headerHeight]="50"
[footerHeight]="50"
[rowHeight]="'auto'"
[limit]="5"
[rows]='rows'
(sort)="onSort($event)">
        <ngx-datatable-column name="{{ 'NAME' | translate }}" prop="displayname">
          <ng-template let-row="row" ngx-datatable-cell-template>
            {{row.displayname}}
          </ng-template>
        </ngx-datatable-column>
        <ngx-datatable-column name="{{ 'EMAIL.LABEL' | translate }}" prop="email">
          <ng-template let-row="row" ngx-datatable-cell-template>
            {{row.email}}
          </ng-template>
        </ngx-datatable-column>
     
         <ngx-datatable-column name="{{ 'EMPLOYEE TYPE' | translate }}" prop="emptname">
          <ng-template let-row="row" ngx-datatable-cell-template>
            {{row.emptname}}
          </ng-template>
        </ngx-datatable-column>      
  </ngx-datatable>`

In ts file fetched the data from db and added the data to rows[]
rows = [];

constructor(private EmployeeService: EmployeeService) {
  
}
ngOnInit() {
	       this.getAllEmployees();
        }
   getAllEmployees() {
	     this.EmployeeService.getAllEmployees().subscribe(
        data => {
            this.rows = data;
       }
      );
   }

**Comment by aravindnaidu09** [comment]
when I used prop it worked.

**Comment by enchanter5525** [comment]
Hello anyone I have ngx datatable. When i add a new recoord it is not showing in the table .any help?

**Comment by shrunk3** [comment]
put a if check on top of ngx-datatable as it checks for dirty data check adding ngIf will resolve this issue

 <div *ngIf="showDataPopulated">
<ngx-datatable></ngx-datatable>
</div>

**Comment by ElbekDeveloper** [comment]
> Hello anyone I have ngx datatable. When i add a new recoord it is not showing in the table .any help?

Same issue
