### ISSUE TITLE
How to use Twitter Bootstrap?

### ISSUE THREAD

**Issue by Caballerog** [swimlane/angular2-data-table#53]
I've been using angular2-data-table with class "material" but anybody kwow how to I can use this library with Twitter Bootstrap? Thanks!

**Comment by amcdnl** [comment]
It doesn't rely on material or anything specific, you can just look at the styles I use in the material CSS and apply bootstrap instead. I don't plan on adding bootstrap theme but if you want to PR it I'll be happy to accept.

**Comment by huynv86** [comment]
I spent a few days but i can't use ngx-datatable with bootsrap even i read your current instruction
I dont know which files i have to change and please give me a direction
thank you so much

**Comment by amcdnl** [comment]
Don't apply the material template and instead custom style it like the bootstrap css.

**Comment by asadsahi** [comment]
@amcdnl I am having difficulty trying to understand how to get boostrap styles applied. is it possible to elaborate a little on bootstrap integration?

Thanks
