### ISSUE TITLE
Scroller ngOnDestroy Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by katsuki-nakatani** [swimlane/angular2-data-table#54]
` StackTrace

zone.js:260 Uncaught EXCEPTION: Error in ./DataTableBody class DataTableBody - inline template:5:6
ORIGINAL EXCEPTION: TypeError: Cannot read property 'removeEventListener' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'removeEventListener' of undefined
`

Scroller.ts ngOnDestroy add check method?
ngOnDestroy() {
    this.parentElement.removeEventListener('scroll');
  }

It was dealt with temporarily 
TableOption include scrollbarV=true

        this.options= new TableOptions({
        headerHeight: 50,
        footerHeight: 50,
        rowHeight: 'auto',
        scrollbarV:true,
        columnMode: ColumnMode.force

**Comment by amcdnl** [comment]
Fixed :)

**Comment by adaur** [comment]
Just so you know, NPM has not been updated to 0.2.3 yet :)

**Comment by amcdnl** [comment]
really? I thought i did, try now plz

**Comment by adaur** [comment]
Awesome, it's working fine! I don't know why the manual modifications didn't work.

Many thanks for your reactivity :+1:

**Comment by katsuki-nakatani** [comment]
@amcdnl 
Thanks!
0.2.3 is non problem
Your work is great!
