### ISSUE TITLE
Got an error: 'Import or export declaration in an ambient module declaration cannot reference module through relative module name'

### ISSUE THREAD

**Issue by dream83619** [swimlane/angular2-data-table#56]
Got an error when compiling:

> ERROR in [default] c:\Codes\angular2\quick-start\node_modules\angular2-data-table\release\angular2-data-table.d.ts:176:4              
> Import or export declaration in an ambient module declaration cannot reference module through relative module name.

How to fix such a kind of error? Thanks.

**Comment by amcdnl** [comment]
The file is there, see: https://github.com/swimlane/angular2-data-table/blob/master/release/angular2-data-table.d.ts

Can you provide a demo maybe?

**Comment by amcdnl** [comment]
Dupe of #55
