### ISSUE TITLE
Production running Error　Can't bind to 'row' since it isn't a known property of 'datatable-body-row

### ISSUE THREAD

**Issue by katsuki-nakatani** [swimlane/angular2-data-table#57]
my Environment angular-cli

develop build is running success 
but production build at running error

stack trace

-

Can't bind to 'row' since it isn't a known property of 'datatable-body-row'.
1. If 'datatable-body-row' is an Angular component and it has 'row' input, then verify that it is part of this module.
2. If 'datatable-body-row' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("    (click)="rowClicked($event, i, row)"
          (keydown)="rowKeydown($event, i, row)"
          [ERROR ->][row]="row">
        </datatable-body-row>
      </div>

**Comment by amcdnl** [comment]
Can you provide a demo?

**Comment by katsuki-nakatani** [comment]
Thanks Reply

Dev buid demo
http://ng2-dt-dev.azurewebsites.net/
Prod build demo
http://ng2-dt-prod.azurewebsites.net/
source code
http://ng2-dt-dev.azurewebsites.net/test-app.zip

Can you Servey?

**Comment by amcdnl** [comment]
Are u on RC5?

**Comment by katsuki-nakatani** [comment]
yes. my development Angular2 RC5

Do you have to be provided to the other？

**Comment by amcdnl** [comment]
Can u give it a try on latest, just made some changes that might resolve this.

**Comment by katsuki-nakatani** [comment]
0.2.4 compile error...
Cannot find module 'angular2-data-table'

**Comment by adaur** [comment]
Yes, it has already been reported in #55. However, if I see the error, it does not prevent TS to compile and the module is working fine.

**Comment by amcdnl** [comment]
Closing in favor of 5
