### ISSUE TITLE
are the demos up to date? they are not work on osx 10.5 chrome 52

### ISSUE THREAD

**Issue by absurdist** [swimlane/angular2-data-table#59]
are the demos up to date? they are not work on osx 10.5 chrome 52
Version 52.0.2743.116 (64-bit)

on https://swimlane.gitbooks.io/angular2-data-table/content/examples/expressive.html#
Instead of a table I just get an image that says 'gist run'

**Comment by amcdnl** [comment]
Ya, was having issues w/ gistrun. Fixed now :)

**Comment by absurdist** [comment]
thanks amcdnl
