### ISSUE TITLE
Release build issues with using directly in Angular

### ISSUE THREAD

**Issue by josdirksen** [swimlane/angular2-data-table#7]
Great work on these tables. Looks really nice and clean. I've been looking at it over the weekend, and have some issues getting the angular2-data-tables.js to work. When using the generated separate JS files directly I can use it from my project.

If I, however, use the angular2-data-table.js file Angular complains about `no directive annotation found on DataTable`. Since it works correctly from the separate .js files (I just copied the dist directory to my own project), I assume something is mangled by jspm.

So for now, I'll continue with the individual js files, but would love to see this also working from your release/npm directly.

**Comment by amcdnl** [comment]
Thanks, appreciate the feedback! It is still very much in progress so excuse some of it. Side note: how'd you find the project?

Interesting, I'm using it in all the demos and on my project with the one file. That looks like an issue with not included `reflect-metadata` sooner. Try tinkering with that and let me know.

**Comment by josdirksen** [comment]
Hmm.. I'll have another go when time permits. I found the project by just searching (I guess on npm) for a datatable compatible with angular2, before I started writing my own one, or wrap an existing one,
