### ISSUE TITLE
Ignore case in sorts options

### ISSUE THREAD

**Issue by fedotxxl** [swimlane/angular2-data-table#73]
I've got `curator.fullName` field and map sort result to URL with format `CURATOR.FULLNAME_DESC`. On page load I read this value and configure `sorts` option and it doesn't work because `data-table` is case sensitive. Can you ignore case?

**Comment by amcdnl** [comment]
Personally, I don't think ignoring case is a good idea. does it not working if you do:

```
{ name: 'Full Name', prop: 'CURATOR.FULLNAME_DESC' } 
```

**Comment by amcdnl** [comment]
Does this answer your question? @fedotxxl

**Comment by fedotxxl** [comment]
yes, you might be right....
