### ISSUE TITLE
last pagination page shows wrong items

### ISSUE THREAD

**Issue by richardstrnad** [swimlane/angular2-data-table#84]
Hi all,

Thanks for this great library!
I just found a small issue, if the last page is called, in some cases there are still 'old' items on it.
https://plnkr.co/edit/1hIoLSJ8TubcX2pow9Ga?p=preview

If you jump to the last page you see first 7 items, click now on page 12 -> 5 items, again -> 3 items
![image](https://cloud.githubusercontent.com/assets/8568786/18015704/11fe00f0-6bc9-11e6-9b75-1a83a45ea5e0.png)

![image](https://cloud.githubusercontent.com/assets/8568786/18015713/18564354-6bc9-11e6-8dd1-3c056008a777.png)

**Comment by zxshinxz** [comment]
Having a same issue here. I was wondering if there's any update?  or anybody working on this issue?

**Comment by amcdnl** [comment]
Sorry, haven't had time. This is where the issue would be located at if you wanna take a stab - https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/Body.ts#L140

**Comment by marjan-georgiev** [comment]
@richardstrnad is this still reproducible? I don't see it in the plunker (you have to update zone.js to latest in there for it to show).

Looks like https://github.com/swimlane/angular2-data-table/pull/122 fixes it.

**Comment by richardstrnad** [comment]
@marjan-georgiev Looks fixed :-) 👍
