### ISSUE TITLE
Spacing of Table Headers

### ISSUE THREAD

**Issue by Tempus35** [swimlane/angular2-data-table#85]
I have found when you have many columns > 10 that the headers for the columns overflow the header. I have scrollbarH on as well, expecting it to allow scrolling over to those off the page columns.

![overflowdatatable](https://cloud.githubusercontent.com/assets/1966467/18070527/405152ae-6e03-11e6-8882-e886642058c5.png)

**Comment by amcdnl** [comment]
Can you make a repo? Thats odd because there is a example of scrollbars in both scenarios like that.

**Comment by Tempus35** [comment]
Yea, I am trying to fork the plunker you have for those and seeing if I can make it do the same.

**Comment by Tempus35** [comment]
I fixed it on my end, it had nothing to do with code persay but how I was initializing that code. I will have relook up the exact solution.
