### ISSUE TITLE
Bunching of Rows on Initial VScroll load

### ISSUE THREAD

**Issue by Tempus35** [swimlane/angular2-data-table#86]
On Initial load of Virtual Scrolling the rows all bunch up as one row and only move out after scrolling some.

![bunchedrows](https://cloud.githubusercontent.com/assets/1966467/18070645/1bc2a41e-6e04-11e6-8d11-053e095f9290.png)

**Comment by amcdnl** [comment]
Can you make a repo case?

**Comment by Tempus35** [comment]
Looking to make a plunker test or something, you think this has to do with the fact that each cell references a template in which the template loads a component, all of this thus would take a bit to load before showing in the table. IE the tables calculations for size might not detect right.

**Comment by jimitndiaye** [comment]
I'm seeing the same problem with a minimal number of rows (about 5).

**Comment by amcdnl** [comment]
Can you guys make a demo? Happy to look.

**Comment by RicardoVaranda** [comment]
#121 seems like the same issue

**Comment by dixso** [comment]
Hi,
You should initialize the data after the view init.

Example:
`
ngAfterViewInit() {
this.rows = [{foo: 'bar'}];
}
`

Regards!

**Comment by amiller29au** [comment]
@dixso - Initializing in ngAfterViewInit did not work.

Duplicate issue here: [https://github.com/swimlane/angular2-data-table/issues/127](url)

**Comment by dixso** [comment]
Hi @amiller29au 
If you use in the @component the property template, I think you should add _AfterContentChecked_ lifecycle.
I think the problem is the load time...

Example:
https://plnkr.co/edit/emZt6RUpsej2RLgfBuQd?p=preview

**Comment by amcdnl** [comment]
@amiller29au fixed this :)!

**Comment by omouse** [comment]
I'm having a similar issue to this right now, the body of the datatable is set to a height of 19px but the row height is set to 50.

the `ng-reflect-body-height` is set to "19", not sure why this is getting calculated incorrectly.

my code looks like this:

```
<ngx-datatable
   class="material"
   [rows]="rows"
   [columns]="columns"
   [loadingIndicator]="loading"
   [scrollbarV]="true"
   [rowHeight]="50"
   [headerHeight]="50"
   [footerHeight]="50"
   ></ngx-datatable>
```

and this is the problem:

![too-small-table](https://cloud.githubusercontent.com/assets/2110497/22411665/45a2a5fc-e674-11e6-8a93-83f7678d9bf8.png)
