### ISSUE TITLE
'Critical dependencies' error

### ISSUE THREAD

**Issue by DzmitryShylovich** [swimlane/angular2-data-table#9]
I use webpack for bundling my project. Table works fine but I get the following warnings/errors in the console http://prntscr.com/bpa9xj

Looks familiar to https://github.com/webpack/webpack/issues/196

**Comment by amcdnl** [comment]
Interesting, I don't use webpack myself but I will definitely look into this. I suspect its something to do with the SystemJS registry.

**Comment by amcdnl** [comment]
Please retry, I'm using webpack now and not having issues :)
