### ISSUE TITLE
Cannot find type definition file for 'core-js'

### ISSUE THREAD

**Issue by daniele-zurico** [swimlane/angular2-data-table#90]
After installed I receive this error:

/node_modules/angular2-data-table/release/models/TableOptions.d.ts:1:1 
    Cannot find type definition file for 'core-js'.

Missed something?

**Comment by amcdnl** [comment]
* sigh * - This issue has been reported before, typescript is such a pain

**Comment by Alber70g** [comment]
You can use `@types/core-js`. Install it using `npm install --save @types/core-js`. 

Then add an entry to tsconfig.json:

```
{
  "compilerOptions": {
    ...
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
   ...
}

```

**Comment by daniele-zurico** [comment]
Unfortunately it goes in conflict with another one:
```
/node_modules/@types/core-js/index.d.ts:21:14 
    Duplicate identifier 'PropertyKey'.
/es6-shim/index.d.ts:3:14 
    Duplicate identifier 'PropertyKey'.
```

**Comment by daniele-zurico** [comment]
I fixed removing mine. I dunno if you want to have that bug open or not or at least update the readme file.
thanks for the support

**Comment by adilmalik393** [comment]
@daniele-zurico  I had the same issue and I followed the same thread. Now I am stuck because I am having  Duplicate identifier 'PropertyKey' errors. Please elaborate how did you solve these errors ?

**Comment by amcdnl** [comment]
This is happening again??

**Comment by adilmalik393** [comment]
@amcdnl Yes. How to solve this issue ?

**Comment by neuberfran** [comment]
@amcdnl Yes. How to solve this issue ?

**Comment by tobi-or-not-tobi** [comment]
@adilmalik393  @neuberfran There are 2 options given by http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/. The preferred option, "Remove core-js from node_modules" doesn't work unfortunately as the ng2-material relies on core-js somehow. I had to "Change es6 to es5" in order to get my app running again.

**Comment by daniele-zurico** [comment]
Add lib:[es5,dom] in your ts config and it works for material as well.
