### ISSUE TITLE
TableOptions are being overwritten with multiple tables on the screen.

### ISSUE THREAD

**Issue by jvanhall** [swimlane/angular2-data-table#91]
We are seeing an issue where the options are overwritten and all the tables on the screen end up with the same options, including columns.

[https://plnkr.co/edit/AKy4ZtuLmpmrMk83F2sW](url)

**Comment by jvanhall** [comment]
Any update on this?  It's preventing us from using the module and we would really like to use it.  Thanks!

**Comment by amcdnl** [comment]
Duplicate of #103, work in progress.
