### ISSUE TITLE
Sort order lost when clearing filter/search

### ISSUE THREAD

**Issue by mashaalmemon** [swimlane/angular2-data-table#99]
Hi There,

Looking at example code, there is no example that "reapplies" sorting on filtered results. To reproduce:
- Sort list in decending order
- Apply filter by typing in text
- Delete all text so that all list values appear

You will notice that while sorting arrow is showing sort is enabled, data is not sorted. Is there a way to call the currently selected sort on the filtered results we are placing back in the "rows" variable?

**Comment by amcdnl** [comment]
Fixed in latest
